local ffi = require 'ffi'
ffi.cdef[[
/* + BEGIN C:/Users/Chris/include/png.h */
enum { PNG_H = 1 };
/* #define PNG_LIBPNG_VER_STRING "1.6.37" ### string, not number "\"1.6.37\"" */
/* #define PNG_HEADER_VERSION_STRING " libpng version 1.6.37 - April 14, 2019\n" ### string, not number "\" libpng version 1.6.37 - April 14, 2019\\n\"" */
enum { PNG_LIBPNG_VER_SONUM = 16 };
enum { PNG_LIBPNG_VER_DLLNUM = 16 };
enum { PNG_LIBPNG_VER_MAJOR = 1 };
enum { PNG_LIBPNG_VER_MINOR = 6 };
enum { PNG_LIBPNG_VER_RELEASE = 37 };
enum { PNG_LIBPNG_VER_BUILD = 0 };
enum { PNG_LIBPNG_BUILD_ALPHA = 1 };
enum { PNG_LIBPNG_BUILD_BETA = 2 };
enum { PNG_LIBPNG_BUILD_RC = 3 };
enum { PNG_LIBPNG_BUILD_STABLE = 4 };
enum { PNG_LIBPNG_BUILD_RELEASE_STATUS_MASK = 7 };
enum { PNG_LIBPNG_BUILD_PATCH = 8 };
enum { PNG_LIBPNG_BUILD_PRIVATE = 16 };
enum { PNG_LIBPNG_BUILD_SPECIAL = 32 };
enum { PNG_LIBPNG_BUILD_BASE_TYPE = 4 };
enum { PNG_LIBPNG_VER = 10637 };
/* ++ BEGIN C:/Users/Chris/include/pnglibconf.h */
/* ++ END   C:/Users/Chris/include/pnglibconf.h */
/* ++ BEGIN C:/Users/Chris/include/pngconf.h */
enum { PNGCONF_H = 1 };
/* +++ BEGIN C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/include/limits.h */
]] require 'ffi.req' 'c.limits' ffi.cdef[[
/* +++ END   C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/include/limits.h */
/* +++ BEGIN C:/Program Files (x86)/Windows Kits/10/include/10.0.22621.0/ucrt/stddef.h */
]] require 'ffi.req' 'c.stddef' ffi.cdef[[
/* +++ END   C:/Program Files (x86)/Windows Kits/10/include/10.0.22621.0/ucrt/stddef.h */
/* +++ BEGIN C:/Program Files (x86)/Windows Kits/10/include/10.0.22621.0/ucrt/stdio.h */
]] require 'ffi.req' 'c.stdio' ffi.cdef[[
/* +++ END   C:/Program Files (x86)/Windows Kits/10/include/10.0.22621.0/ucrt/stdio.h */
/* +++ BEGIN C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/include/setjmp.h */
]] require 'ffi.req' 'c.setjmp' ffi.cdef[[
/* +++ END   C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/include/setjmp.h */
/* +++ BEGIN C:/Program Files (x86)/Windows Kits/10/include/10.0.22621.0/ucrt/time.h */
]] require 'ffi.req' 'c.time' ffi.cdef[[
/* +++ END   C:/Program Files (x86)/Windows Kits/10/include/10.0.22621.0/ucrt/time.h */
enum { PNG_CONST = 0 };
enum { PNG_USE_READ_MACROS = 1 };
enum { PNGCAPI = 0 };
/* #    define PNG_DLL_EXPORT __declspec(dllexport) ### string, not number "__declspec(dllexport)" */
/* #      define PNG_DLL_IMPORT __declspec(dllimport) ### string, not number "__declspec(dllimport)" */
enum { PNGCBAPI = 0 };
enum { PNGAPI = 0 };
enum { PNG_IMPEXP = 1 };
enum { PNG_EMPTY = 1 };
enum { PNG_PEDANTIC_WARNINGS_SUPPORTED = 1 };
enum { PNG_USE_RESULT = 1 };
/* #      define PNG_NORETURN   __declspec(noreturn) ### string, not number "__declspec(noreturn)" */
/* #        define PNG_ALLOCATED __declspec(restrict) ### string, not number "__declspec(restrict)" */
/* #      define PNG_DEPRECATED __declspec(deprecated) ### string, not number "__declspec(deprecated)" */
/* #      define PNG_PRIVATE __declspec(deprecated) ### string, not number "__declspec(deprecated)" */
/* #        define PNG_RESTRICT __restrict ### string, not number "__restrict" */
typedef unsigned char png_byte;
typedef short png_int_16;
typedef unsigned short png_uint_16;
typedef int png_int_32;
typedef unsigned int png_uint_32;
typedef size_t png_size_t;
typedef ptrdiff_t png_ptrdiff_t;
typedef size_t png_alloc_size_t;
typedef png_int_32 png_fixed_point;
typedef void * png_voidp;
typedef const void * png_const_voidp;
typedef png_byte * png_bytep;
typedef const png_byte * png_const_bytep;
typedef png_uint_32 * png_uint_32p;
typedef const png_uint_32 * png_const_uint_32p;
typedef png_int_32 * png_int_32p;
typedef const png_int_32 * png_const_int_32p;
typedef png_uint_16 * png_uint_16p;
typedef const png_uint_16 * png_const_uint_16p;
typedef png_int_16 * png_int_16p;
typedef const png_int_16 * png_const_int_16p;
typedef char * png_charp;
typedef const char * png_const_charp;
typedef png_fixed_point * png_fixed_point_p;
typedef const png_fixed_point * png_const_fixed_point_p;
typedef size_t * png_size_tp;
typedef const size_t * png_const_size_tp;
typedef FILE * png_FILE_p;
typedef double * png_doublep;
typedef const double * png_const_doublep;
typedef png_byte * * png_bytepp;
typedef png_uint_32 * * png_uint_32pp;
typedef png_int_32 * * png_int_32pp;
typedef png_uint_16 * * png_uint_16pp;
typedef png_int_16 * * png_int_16pp;
typedef const char * * png_const_charpp;
typedef char * * png_charpp;
typedef png_fixed_point * * png_fixed_point_pp;
typedef double * * png_doublepp;
typedef char * * * png_charppp;
/* ++ END   C:/Users/Chris/include/pngconf.h */
enum { PNG_LIBPNG_BUILD_TYPE = 4 };
/* #define png_libpng_ver png_get_header_ver(NULL) ### string, not number "png_get_header_ver(NULL)" */
typedef char* png_libpng_version_1_6_37;
typedef struct png_struct_def png_struct;
typedef const png_struct * png_const_structp;
typedef png_struct * png_structp;
typedef png_struct * * png_structpp;
typedef struct png_info_def png_info;
typedef png_info * png_infop;
typedef const png_info * png_const_infop;
typedef png_info * * png_infopp;
typedef png_struct * png_structrp;
typedef const png_struct * png_const_structrp;
typedef png_info * png_inforp;
typedef const png_info * png_const_inforp;
typedef struct png_color_struct {
	png_byte red;
	png_byte green;
	png_byte blue;
} png_color;
typedef png_color * png_colorp;
typedef const png_color * png_const_colorp;
typedef png_color * * png_colorpp;
typedef struct png_color_16_struct {
	png_byte index;
	png_uint_16 red;
	png_uint_16 green;
	png_uint_16 blue;
	png_uint_16 gray;
} png_color_16;
typedef png_color_16 * png_color_16p;
typedef const png_color_16 * png_const_color_16p;
typedef png_color_16 * * png_color_16pp;
typedef struct png_color_8_struct {
	png_byte red;
	png_byte green;
	png_byte blue;
	png_byte gray;
	png_byte alpha;
} png_color_8;
typedef png_color_8 * png_color_8p;
typedef const png_color_8 * png_const_color_8p;
typedef png_color_8 * * png_color_8pp;
typedef struct png_sPLT_entry_struct {
	png_uint_16 red;
	png_uint_16 green;
	png_uint_16 blue;
	png_uint_16 alpha;
	png_uint_16 frequency;
} png_sPLT_entry;
typedef png_sPLT_entry * png_sPLT_entryp;
typedef const png_sPLT_entry * png_const_sPLT_entryp;
typedef png_sPLT_entry * * png_sPLT_entrypp;
typedef struct png_sPLT_struct {
	png_charp name;
	png_byte depth;
	png_sPLT_entryp entries;
	png_int_32 nentries;
} png_sPLT_t;
typedef png_sPLT_t * png_sPLT_tp;
typedef const png_sPLT_t * png_const_sPLT_tp;
typedef png_sPLT_t * * png_sPLT_tpp;
typedef struct png_text_struct {
	int compression;
	png_charp key;
	png_charp text;
	size_t text_length;
	size_t itxt_length;
	png_charp lang;
	png_charp lang_key;
} png_text;
typedef png_text * png_textp;
typedef const png_text * png_const_textp;
typedef png_text * * png_textpp;
enum { PNG_TEXT_COMPRESSION_NONE_WR = -3 };
enum { PNG_TEXT_COMPRESSION_zTXt_WR = -2 };
enum { PNG_TEXT_COMPRESSION_NONE = -1 };
enum { PNG_TEXT_COMPRESSION_zTXt = 0 };
enum { PNG_ITXT_COMPRESSION_NONE = 1 };
enum { PNG_ITXT_COMPRESSION_zTXt = 2 };
enum { PNG_TEXT_COMPRESSION_LAST = 3 };
typedef struct png_time_struct {
	png_uint_16 year;
	png_byte month;
	png_byte day;
	png_byte hour;
	png_byte minute;
	png_byte second;
} png_time;
typedef png_time * png_timep;
typedef const png_time * png_const_timep;
typedef png_time * * png_timepp;
typedef struct png_unknown_chunk_t {
	png_byte name[5];
	png_byte *data;
	size_t size;
	png_byte location;
} png_unknown_chunk;
typedef png_unknown_chunk * png_unknown_chunkp;
typedef const png_unknown_chunk * png_const_unknown_chunkp;
typedef png_unknown_chunk * * png_unknown_chunkpp;
enum { PNG_HAVE_IHDR = 1 };
enum { PNG_HAVE_PLTE = 2 };
enum { PNG_AFTER_IDAT = 8 };
/* #define PNG_UINT_31_MAX ((png_uint_32)0x7fffffffL) ### string, not number "((png_uint_32)0x7fffffffL)" */
/* #define PNG_UINT_32_MAX ((png_uint_32)(-1)) ### string, not number "((png_uint_32)(-1))" */
/* #define PNG_SIZE_MAX ((size_t)(-1)) ### string, not number "((size_t)(-1))" */
enum { PNG_FP_1 = 100000 };
enum { PNG_FP_HALF = 50000 };
/* #define PNG_FP_MAX  ((png_fixed_point)0x7fffffffL) ### string, not number "((png_fixed_point)0x7fffffffL)" */
/* #define PNG_FP_MIN  (-PNG_FP_MAX) ### string, not number "(-PNG_FP_MAX)" */
enum { PNG_COLOR_MASK_PALETTE = 1 };
enum { PNG_COLOR_MASK_COLOR = 2 };
enum { PNG_COLOR_MASK_ALPHA = 4 };
enum { PNG_COLOR_TYPE_GRAY = 0 };
enum { PNG_COLOR_TYPE_PALETTE = 3 };
enum { PNG_COLOR_TYPE_RGB = 2 };
enum { PNG_COLOR_TYPE_RGB_ALPHA = 6 };
enum { PNG_COLOR_TYPE_GRAY_ALPHA = 4 };
enum { PNG_COLOR_TYPE_RGBA = 6 };
enum { PNG_COLOR_TYPE_GA = 4 };
enum { PNG_COMPRESSION_TYPE_BASE = 0 };
enum { PNG_COMPRESSION_TYPE_DEFAULT = 0 };
enum { PNG_FILTER_TYPE_BASE = 0 };
enum { PNG_INTRAPIXEL_DIFFERENCING = 64 };
enum { PNG_FILTER_TYPE_DEFAULT = 0 };
enum { PNG_INTERLACE_NONE = 0 };
enum { PNG_INTERLACE_ADAM7 = 1 };
enum { PNG_INTERLACE_LAST = 2 };
enum { PNG_OFFSET_PIXEL = 0 };
enum { PNG_OFFSET_MICROMETER = 1 };
enum { PNG_OFFSET_LAST = 2 };
enum { PNG_EQUATION_LINEAR = 0 };
enum { PNG_EQUATION_BASE_E = 1 };
enum { PNG_EQUATION_ARBITRARY = 2 };
enum { PNG_EQUATION_HYPERBOLIC = 3 };
enum { PNG_EQUATION_LAST = 4 };
enum { PNG_SCALE_UNKNOWN = 0 };
enum { PNG_SCALE_METER = 1 };
enum { PNG_SCALE_RADIAN = 2 };
enum { PNG_SCALE_LAST = 3 };
enum { PNG_RESOLUTION_UNKNOWN = 0 };
enum { PNG_RESOLUTION_METER = 1 };
enum { PNG_RESOLUTION_LAST = 2 };
enum { PNG_sRGB_INTENT_PERCEPTUAL = 0 };
enum { PNG_sRGB_INTENT_RELATIVE = 1 };
enum { PNG_sRGB_INTENT_SATURATION = 2 };
enum { PNG_sRGB_INTENT_ABSOLUTE = 3 };
enum { PNG_sRGB_INTENT_LAST = 4 };
enum { PNG_KEYWORD_MAX_LENGTH = 79 };
enum { PNG_MAX_PALETTE_LENGTH = 256 };
enum { PNG_INFO_gAMA = 1 };
enum { PNG_INFO_sBIT = 2 };
enum { PNG_INFO_cHRM = 4 };
enum { PNG_INFO_PLTE = 8 };
enum { PNG_INFO_tRNS = 16 };
enum { PNG_INFO_bKGD = 32 };
enum { PNG_INFO_hIST = 64 };
enum { PNG_INFO_pHYs = 128 };
enum { PNG_INFO_oFFs = 256 };
enum { PNG_INFO_tIME = 512 };
enum { PNG_INFO_pCAL = 1024 };
enum { PNG_INFO_sRGB = 2048 };
enum { PNG_INFO_iCCP = 4096 };
enum { PNG_INFO_sPLT = 8192 };
enum { PNG_INFO_sCAL = 16384 };
enum { PNG_INFO_IDAT = 32768 };
enum { PNG_INFO_eXIf = 65536 };
typedef struct png_row_info_struct {
	png_uint_32 width;
	size_t rowbytes;
	png_byte color_type;
	png_byte bit_depth;
	png_byte channels;
	png_byte pixel_depth;
} png_row_info;
typedef png_row_info * png_row_infop;
typedef png_row_info * * png_row_infopp;
typedef void (__cdecl *png_error_ptr) (png_structp, png_const_charp);
typedef void (__cdecl *png_rw_ptr) (png_structp, png_bytep, size_t);
typedef void (__cdecl *png_flush_ptr) (png_structp);
typedef void (__cdecl *png_read_status_ptr) (png_structp, png_uint_32, int);
typedef void (__cdecl *png_write_status_ptr) (png_structp, png_uint_32, int);
typedef void (__cdecl *png_progressive_info_ptr) (png_structp, png_infop);
typedef void (__cdecl *png_progressive_end_ptr) (png_structp, png_infop);
typedef void (__cdecl *png_progressive_row_ptr) (png_structp, png_bytep, png_uint_32, int);
typedef void (__cdecl *png_user_transform_ptr) (png_structp, png_row_infop, png_bytep);
typedef int (__cdecl *png_user_chunk_ptr) (png_structp, png_unknown_chunkp);
typedef void (__cdecl *png_longjmp_ptr) (jmp_buf, int);
enum { PNG_TRANSFORM_IDENTITY = 0 };
enum { PNG_TRANSFORM_STRIP_16 = 1 };
enum { PNG_TRANSFORM_STRIP_ALPHA = 2 };
enum { PNG_TRANSFORM_PACKING = 4 };
enum { PNG_TRANSFORM_PACKSWAP = 8 };
enum { PNG_TRANSFORM_EXPAND = 16 };
enum { PNG_TRANSFORM_INVERT_MONO = 32 };
enum { PNG_TRANSFORM_SHIFT = 64 };
enum { PNG_TRANSFORM_BGR = 128 };
enum { PNG_TRANSFORM_SWAP_ALPHA = 256 };
enum { PNG_TRANSFORM_SWAP_ENDIAN = 512 };
enum { PNG_TRANSFORM_INVERT_ALPHA = 1024 };
enum { PNG_TRANSFORM_STRIP_FILLER = 2048 };
enum { PNG_TRANSFORM_STRIP_FILLER_BEFORE = 2048 };
enum { PNG_TRANSFORM_STRIP_FILLER_AFTER = 4096 };
enum { PNG_TRANSFORM_GRAY_TO_RGB = 8192 };
enum { PNG_TRANSFORM_EXPAND_16 = 16384 };
enum { PNG_TRANSFORM_SCALE_16 = 32768 };
enum { PNG_FLAG_MNG_EMPTY_PLTE = 1 };
enum { PNG_FLAG_MNG_FILTER_64 = 4 };
enum { PNG_ALL_MNG_FEATURES = 5 };
typedef png_voidp (__cdecl *png_malloc_ptr) (png_structp, png_alloc_size_t);
typedef void (__cdecl *png_free_ptr) (png_structp, png_voidp);
extern png_uint_32 (__cdecl png_access_version_number) (void);
extern void (__cdecl png_set_sig_bytes) (png_structrp png_ptr, int num_bytes);
extern int (__cdecl png_sig_cmp) (png_const_bytep sig, size_t start, size_t num_to_check);
extern png_structp (__cdecl png_create_read_struct) (png_const_charp user_png_ver, png_voidp error_ptr, png_error_ptr error_fn, png_error_ptr warn_fn);
extern png_structp (__cdecl png_create_write_struct) (png_const_charp user_png_ver, png_voidp error_ptr, png_error_ptr error_fn, png_error_ptr warn_fn);
extern size_t (__cdecl png_get_compression_buffer_size) (png_const_structrp png_ptr);
extern void (__cdecl png_set_compression_buffer_size) (png_structrp png_ptr, size_t size);
extern jmp_buf* (__cdecl png_set_longjmp_fn) (png_structrp png_ptr, png_longjmp_ptr longjmp_fn, size_t jmp_buf_size);
extern void (__cdecl png_longjmp) (png_const_structrp png_ptr, int val);
extern int (__cdecl png_reset_zstream) (png_structrp png_ptr);
extern png_structp (__cdecl png_create_read_struct_2) (png_const_charp user_png_ver, png_voidp error_ptr, png_error_ptr error_fn, png_error_ptr warn_fn, png_voidp mem_ptr, png_malloc_ptr malloc_fn, png_free_ptr free_fn);
extern png_structp (__cdecl png_create_write_struct_2) (png_const_charp user_png_ver, png_voidp error_ptr, png_error_ptr error_fn, png_error_ptr warn_fn, png_voidp mem_ptr, png_malloc_ptr malloc_fn, png_free_ptr free_fn);
extern void (__cdecl png_write_sig) (png_structrp png_ptr);
extern void (__cdecl png_write_chunk) (png_structrp png_ptr, png_const_bytep chunk_name, png_const_bytep data, size_t length);
extern void (__cdecl png_write_chunk_start) (png_structrp png_ptr, png_const_bytep chunk_name, png_uint_32 length);
extern void (__cdecl png_write_chunk_data) (png_structrp png_ptr, png_const_bytep data, size_t length);
extern void (__cdecl png_write_chunk_end) (png_structrp png_ptr);
extern png_infop (__cdecl png_create_info_struct) (png_const_structrp png_ptr);
extern void (__cdecl png_info_init_3) (png_infopp info_ptr, size_t png_info_struct_size);
extern void (__cdecl png_write_info_before_PLTE) (png_structrp png_ptr, png_const_inforp info_ptr);
extern void (__cdecl png_write_info) (png_structrp png_ptr, png_const_inforp info_ptr);
extern void (__cdecl png_read_info) (png_structrp png_ptr, png_inforp info_ptr);
extern png_const_charp (__cdecl png_convert_to_rfc1123) (png_structrp png_ptr, png_const_timep ptime);
extern int (__cdecl png_convert_to_rfc1123_buffer) (char out[29], png_const_timep ptime);
extern void (__cdecl png_convert_from_struct_tm) (png_timep ptime, const struct tm * ttime);
extern void (__cdecl png_convert_from_time_t) (png_timep ptime, time_t ttime);
extern void (__cdecl png_set_expand) (png_structrp png_ptr);
extern void (__cdecl png_set_expand_gray_1_2_4_to_8) (png_structrp png_ptr);
extern void (__cdecl png_set_palette_to_rgb) (png_structrp png_ptr);
extern void (__cdecl png_set_tRNS_to_alpha) (png_structrp png_ptr);
extern void (__cdecl png_set_expand_16) (png_structrp png_ptr);
extern void (__cdecl png_set_bgr) (png_structrp png_ptr);
extern void (__cdecl png_set_gray_to_rgb) (png_structrp png_ptr);
enum { PNG_ERROR_ACTION_NONE = 1 };
enum { PNG_ERROR_ACTION_WARN = 2 };
enum { PNG_ERROR_ACTION_ERROR = 3 };
enum { PNG_RGB_TO_GRAY_DEFAULT = -1 };
extern void (__cdecl png_set_rgb_to_gray) (png_structrp png_ptr, int error_action, double red, double green);
extern void (__cdecl png_set_rgb_to_gray_fixed) (png_structrp png_ptr, int error_action, png_fixed_point red, png_fixed_point green);
extern png_byte (__cdecl png_get_rgb_to_gray_status) (png_const_structrp png_ptr);
extern void (__cdecl png_build_grayscale_palette) (int bit_depth, png_colorp palette);
enum { PNG_ALPHA_PNG = 0 };
enum { PNG_ALPHA_STANDARD = 1 };
enum { PNG_ALPHA_ASSOCIATED = 1 };
enum { PNG_ALPHA_PREMULTIPLIED = 1 };
enum { PNG_ALPHA_OPTIMIZED = 2 };
enum { PNG_ALPHA_BROKEN = 3 };
extern void (__cdecl png_set_alpha_mode) (png_structrp png_ptr, int mode, double output_gamma);
extern void (__cdecl png_set_alpha_mode_fixed) (png_structrp png_ptr, int mode, png_fixed_point output_gamma);
enum { PNG_DEFAULT_sRGB = -1 };
enum { PNG_GAMMA_MAC_18 = -2 };
enum { PNG_GAMMA_sRGB = 220000 };
enum { PNG_GAMMA_LINEAR = 100000 };
extern void (__cdecl png_set_strip_alpha) (png_structrp png_ptr);
extern void (__cdecl png_set_swap_alpha) (png_structrp png_ptr);
extern void (__cdecl png_set_invert_alpha) (png_structrp png_ptr);
extern void (__cdecl png_set_filler) (png_structrp png_ptr, png_uint_32 filler, int flags);
enum { PNG_FILLER_BEFORE = 0 };
enum { PNG_FILLER_AFTER = 1 };
extern void (__cdecl png_set_add_alpha) (png_structrp png_ptr, png_uint_32 filler, int flags);
extern void (__cdecl png_set_swap) (png_structrp png_ptr);
extern void (__cdecl png_set_packing) (png_structrp png_ptr);
extern void (__cdecl png_set_packswap) (png_structrp png_ptr);
extern void (__cdecl png_set_shift) (png_structrp png_ptr, png_const_color_8p true_bits);
extern int (__cdecl png_set_interlace_handling) (png_structrp png_ptr);
extern void (__cdecl png_set_invert_mono) (png_structrp png_ptr);
extern void (__cdecl png_set_background) (png_structrp png_ptr, png_const_color_16p background_color, int background_gamma_code, int need_expand, double background_gamma);
extern void (__cdecl png_set_background_fixed) (png_structrp png_ptr, png_const_color_16p background_color, int background_gamma_code, int need_expand, png_fixed_point background_gamma);
enum { PNG_BACKGROUND_GAMMA_UNKNOWN = 0 };
enum { PNG_BACKGROUND_GAMMA_SCREEN = 1 };
enum { PNG_BACKGROUND_GAMMA_FILE = 2 };
enum { PNG_BACKGROUND_GAMMA_UNIQUE = 3 };
extern void (__cdecl png_set_scale_16) (png_structrp png_ptr);
enum { PNG_READ_16_TO_8_SUPPORTED = 1 };
extern void (__cdecl png_set_strip_16) (png_structrp png_ptr);
extern void (__cdecl png_set_quantize) (png_structrp png_ptr, png_colorp palette, int num_palette, int maximum_colors, png_const_uint_16p histogram, int full_quantize);
/* #define PNG_GAMMA_THRESHOLD (PNG_GAMMA_THRESHOLD_FIXED*.00001) ### string, not number "(PNG_GAMMA_THRESHOLD_FIXED*.00001)" */
extern void (__cdecl png_set_gamma) (png_structrp png_ptr, double screen_gamma, double override_file_gamma);
extern void (__cdecl png_set_gamma_fixed) (png_structrp png_ptr, png_fixed_point screen_gamma, png_fixed_point override_file_gamma);
extern void (__cdecl png_set_flush) (png_structrp png_ptr, int nrows);
extern void (__cdecl png_write_flush) (png_structrp png_ptr);
extern void (__cdecl png_start_read_image) (png_structrp png_ptr);
extern void (__cdecl png_read_update_info) (png_structrp png_ptr, png_inforp info_ptr);
extern void (__cdecl png_read_rows) (png_structrp png_ptr, png_bytepp row, png_bytepp display_row, png_uint_32 num_rows);
extern void (__cdecl png_read_row) (png_structrp png_ptr, png_bytep row, png_bytep display_row);
extern void (__cdecl png_read_image) (png_structrp png_ptr, png_bytepp image);
extern void (__cdecl png_write_row) (png_structrp png_ptr, png_const_bytep row);
extern void (__cdecl png_write_rows) (png_structrp png_ptr, png_bytepp row, png_uint_32 num_rows);
extern void (__cdecl png_write_image) (png_structrp png_ptr, png_bytepp image);
extern void (__cdecl png_write_end) (png_structrp png_ptr, png_inforp info_ptr);
extern void (__cdecl png_read_end) (png_structrp png_ptr, png_inforp info_ptr);
extern void (__cdecl png_destroy_info_struct) (png_const_structrp png_ptr, png_infopp info_ptr_ptr);
extern void (__cdecl png_destroy_read_struct) (png_structpp png_ptr_ptr, png_infopp info_ptr_ptr, png_infopp end_info_ptr_ptr);
extern void (__cdecl png_destroy_write_struct) (png_structpp png_ptr_ptr, png_infopp info_ptr_ptr);
extern void (__cdecl png_set_crc_action) (png_structrp png_ptr, int crit_action, int ancil_action);
enum { PNG_CRC_DEFAULT = 0 };
enum { PNG_CRC_ERROR_QUIT = 1 };
enum { PNG_CRC_WARN_DISCARD = 2 };
enum { PNG_CRC_WARN_USE = 3 };
enum { PNG_CRC_QUIET_USE = 4 };
enum { PNG_CRC_NO_CHANGE = 5 };
extern void (__cdecl png_set_filter) (png_structrp png_ptr, int method, int filters);
enum { PNG_NO_FILTERS = 0 };
enum { PNG_FILTER_NONE = 8 };
enum { PNG_FILTER_SUB = 16 };
enum { PNG_FILTER_UP = 32 };
enum { PNG_FILTER_AVG = 64 };
enum { PNG_FILTER_PAETH = 128 };
enum { PNG_FAST_FILTERS = 56 };
enum { PNG_ALL_FILTERS = 248 };
enum { PNG_FILTER_VALUE_NONE = 0 };
enum { PNG_FILTER_VALUE_SUB = 1 };
enum { PNG_FILTER_VALUE_UP = 2 };
enum { PNG_FILTER_VALUE_AVG = 3 };
enum { PNG_FILTER_VALUE_PAETH = 4 };
enum { PNG_FILTER_VALUE_LAST = 5 };
extern void (__cdecl png_set_filter_heuristics) (png_structrp png_ptr, int heuristic_method, int num_weights, png_const_doublep filter_weights, png_const_doublep filter_costs);
extern void (__cdecl png_set_filter_heuristics_fixed) (png_structrp png_ptr, int heuristic_method, int num_weights, png_const_fixed_point_p filter_weights, png_const_fixed_point_p filter_costs);
enum { PNG_FILTER_HEURISTIC_DEFAULT = 0 };
enum { PNG_FILTER_HEURISTIC_UNWEIGHTED = 1 };
enum { PNG_FILTER_HEURISTIC_WEIGHTED = 2 };
enum { PNG_FILTER_HEURISTIC_LAST = 3 };
extern void (__cdecl png_set_compression_level) (png_structrp png_ptr, int level);
extern void (__cdecl png_set_compression_mem_level) (png_structrp png_ptr, int mem_level);
extern void (__cdecl png_set_compression_strategy) (png_structrp png_ptr, int strategy);
extern void (__cdecl png_set_compression_window_bits) (png_structrp png_ptr, int window_bits);
extern void (__cdecl png_set_compression_method) (png_structrp png_ptr, int method);
extern void (__cdecl png_set_text_compression_level) (png_structrp png_ptr, int level);
extern void (__cdecl png_set_text_compression_mem_level) (png_structrp png_ptr, int mem_level);
extern void (__cdecl png_set_text_compression_strategy) (png_structrp png_ptr, int strategy);
extern void (__cdecl png_set_text_compression_window_bits) (png_structrp png_ptr, int window_bits);
extern void (__cdecl png_set_text_compression_method) (png_structrp png_ptr, int method);
extern void (__cdecl png_init_io) (png_structrp png_ptr, png_FILE_p fp);
extern void (__cdecl png_set_error_fn) (png_structrp png_ptr, png_voidp error_ptr, png_error_ptr error_fn, png_error_ptr warning_fn);
extern png_voidp (__cdecl png_get_error_ptr) (png_const_structrp png_ptr);
extern void (__cdecl png_set_write_fn) (png_structrp png_ptr, png_voidp io_ptr, png_rw_ptr write_data_fn, png_flush_ptr output_flush_fn);
extern void (__cdecl png_set_read_fn) (png_structrp png_ptr, png_voidp io_ptr, png_rw_ptr read_data_fn);
extern png_voidp (__cdecl png_get_io_ptr) (png_const_structrp png_ptr);
extern void (__cdecl png_set_read_status_fn) (png_structrp png_ptr, png_read_status_ptr read_row_fn);
extern void (__cdecl png_set_write_status_fn) (png_structrp png_ptr, png_write_status_ptr write_row_fn);
extern void (__cdecl png_set_mem_fn) (png_structrp png_ptr, png_voidp mem_ptr, png_malloc_ptr malloc_fn, png_free_ptr free_fn);
extern png_voidp (__cdecl png_get_mem_ptr) (png_const_structrp png_ptr);
extern void (__cdecl png_set_read_user_transform_fn) (png_structrp png_ptr, png_user_transform_ptr read_user_transform_fn);
extern void (__cdecl png_set_write_user_transform_fn) (png_structrp png_ptr, png_user_transform_ptr write_user_transform_fn);
extern void (__cdecl png_set_user_transform_info) (png_structrp png_ptr, png_voidp user_transform_ptr, int user_transform_depth, int user_transform_channels);
extern png_voidp (__cdecl png_get_user_transform_ptr) (png_const_structrp png_ptr);
extern png_uint_32 (__cdecl png_get_current_row_number) (png_const_structrp);
extern png_byte (__cdecl png_get_current_pass_number) (png_const_structrp);
extern void (__cdecl png_set_read_user_chunk_fn) (png_structrp png_ptr, png_voidp user_chunk_ptr, png_user_chunk_ptr read_user_chunk_fn);
extern png_voidp (__cdecl png_get_user_chunk_ptr) (png_const_structrp png_ptr);
extern void (__cdecl png_set_progressive_read_fn) (png_structrp png_ptr, png_voidp progressive_ptr, png_progressive_info_ptr info_fn, png_progressive_row_ptr row_fn, png_progressive_end_ptr end_fn);
extern png_voidp (__cdecl png_get_progressive_ptr) (png_const_structrp png_ptr);
extern void (__cdecl png_process_data) (png_structrp png_ptr, png_inforp info_ptr, png_bytep buffer, size_t buffer_size);
extern size_t (__cdecl png_process_data_pause) (png_structrp, int save);
extern png_uint_32 (__cdecl png_process_data_skip) (png_structrp);
extern void (__cdecl png_progressive_combine_row) (png_const_structrp png_ptr, png_bytep old_row, png_const_bytep new_row);
extern png_voidp (__cdecl png_malloc) (png_const_structrp png_ptr, png_alloc_size_t size);
extern png_voidp (__cdecl png_calloc) (png_const_structrp png_ptr, png_alloc_size_t size);
extern png_voidp (__cdecl png_malloc_warn) (png_const_structrp png_ptr, png_alloc_size_t size);
extern void (__cdecl png_free) (png_const_structrp png_ptr, png_voidp ptr);
extern void (__cdecl png_free_data) (png_const_structrp png_ptr, png_inforp info_ptr, png_uint_32 free_me, int num);
extern void (__cdecl png_data_freer) (png_const_structrp png_ptr, png_inforp info_ptr, int freer, png_uint_32 mask);
enum { PNG_DESTROY_WILL_FREE_DATA = 1 };
enum { PNG_SET_WILL_FREE_DATA = 1 };
enum { PNG_USER_WILL_FREE_DATA = 2 };
enum { PNG_FREE_HIST = 8 };
enum { PNG_FREE_ICCP = 16 };
enum { PNG_FREE_SPLT = 32 };
enum { PNG_FREE_ROWS = 64 };
enum { PNG_FREE_PCAL = 128 };
enum { PNG_FREE_SCAL = 256 };
enum { PNG_FREE_UNKN = 512 };
enum { PNG_FREE_PLTE = 4096 };
enum { PNG_FREE_TRNS = 8192 };
enum { PNG_FREE_TEXT = 16384 };
enum { PNG_FREE_EXIF = 32768 };
enum { PNG_FREE_ALL = 65535 };
enum { PNG_FREE_MUL = 16928 };
extern png_voidp (__cdecl png_malloc_default) (png_const_structrp png_ptr, png_alloc_size_t size);
extern void (__cdecl png_free_default) (png_const_structrp png_ptr, png_voidp ptr);
extern void (__cdecl png_error) (png_const_structrp png_ptr, png_const_charp error_message);
extern void (__cdecl png_chunk_error) (png_const_structrp png_ptr, png_const_charp error_message);
extern void (__cdecl png_warning) (png_const_structrp png_ptr, png_const_charp warning_message);
extern void (__cdecl png_chunk_warning) (png_const_structrp png_ptr, png_const_charp warning_message);
extern void (__cdecl png_benign_error) (png_const_structrp png_ptr, png_const_charp warning_message);
extern void (__cdecl png_chunk_benign_error) (png_const_structrp png_ptr, png_const_charp warning_message);
extern void (__cdecl png_set_benign_errors) (png_structrp png_ptr, int allowed);
extern png_uint_32 (__cdecl png_get_valid) (png_const_structrp png_ptr, png_const_inforp info_ptr, png_uint_32 flag);
extern size_t (__cdecl png_get_rowbytes) (png_const_structrp png_ptr, png_const_inforp info_ptr);
extern png_bytepp (__cdecl png_get_rows) (png_const_structrp png_ptr, png_const_inforp info_ptr);
extern void (__cdecl png_set_rows) (png_const_structrp png_ptr, png_inforp info_ptr, png_bytepp row_pointers);
extern png_byte (__cdecl png_get_channels) (png_const_structrp png_ptr, png_const_inforp info_ptr);
extern png_uint_32 (__cdecl png_get_image_width) (png_const_structrp png_ptr, png_const_inforp info_ptr);
extern png_uint_32 (__cdecl png_get_image_height) (png_const_structrp png_ptr, png_const_inforp info_ptr);
extern png_byte (__cdecl png_get_bit_depth) (png_const_structrp png_ptr, png_const_inforp info_ptr);
extern png_byte (__cdecl png_get_color_type) (png_const_structrp png_ptr, png_const_inforp info_ptr);
extern png_byte (__cdecl png_get_filter_type) (png_const_structrp png_ptr, png_const_inforp info_ptr);
extern png_byte (__cdecl png_get_interlace_type) (png_const_structrp png_ptr, png_const_inforp info_ptr);
extern png_byte (__cdecl png_get_compression_type) (png_const_structrp png_ptr, png_const_inforp info_ptr);
extern png_uint_32 (__cdecl png_get_pixels_per_meter) (png_const_structrp png_ptr, png_const_inforp info_ptr);
extern png_uint_32 (__cdecl png_get_x_pixels_per_meter) (png_const_structrp png_ptr, png_const_inforp info_ptr);
extern png_uint_32 (__cdecl png_get_y_pixels_per_meter) (png_const_structrp png_ptr, png_const_inforp info_ptr);
extern float (__cdecl png_get_pixel_aspect_ratio) (png_const_structrp png_ptr, png_const_inforp info_ptr);
extern png_fixed_point (__cdecl png_get_pixel_aspect_ratio_fixed) (png_const_structrp png_ptr, png_const_inforp info_ptr);
extern png_int_32 (__cdecl png_get_x_offset_pixels) (png_const_structrp png_ptr, png_const_inforp info_ptr);
extern png_int_32 (__cdecl png_get_y_offset_pixels) (png_const_structrp png_ptr, png_const_inforp info_ptr);
extern png_int_32 (__cdecl png_get_x_offset_microns) (png_const_structrp png_ptr, png_const_inforp info_ptr);
extern png_int_32 (__cdecl png_get_y_offset_microns) (png_const_structrp png_ptr, png_const_inforp info_ptr);
extern png_const_bytep (__cdecl png_get_signature) (png_const_structrp png_ptr, png_const_inforp info_ptr);
extern png_uint_32 (__cdecl png_get_bKGD) (png_const_structrp png_ptr, png_inforp info_ptr, png_color_16p *background);
extern void (__cdecl png_set_bKGD) (png_const_structrp png_ptr, png_inforp info_ptr, png_const_color_16p background);
extern png_uint_32 (__cdecl png_get_cHRM) (png_const_structrp png_ptr, png_const_inforp info_ptr, double *white_x, double *white_y, double *red_x, double *red_y, double *green_x, double *green_y, double *blue_x, double *blue_y);
extern png_uint_32 (__cdecl png_get_cHRM_XYZ) (png_const_structrp png_ptr, png_const_inforp info_ptr, double *red_X, double *red_Y, double *red_Z, double *green_X, double *green_Y, double *green_Z, double *blue_X, double *blue_Y, double *blue_Z);
extern png_uint_32 (__cdecl png_get_cHRM_fixed) (png_const_structrp png_ptr, png_const_inforp info_ptr, png_fixed_point *int_white_x, png_fixed_point *int_white_y, png_fixed_point *int_red_x, png_fixed_point *int_red_y, png_fixed_point *int_green_x, png_fixed_point *int_green_y, png_fixed_point *int_blue_x, png_fixed_point *int_blue_y);
extern png_uint_32 (__cdecl png_get_cHRM_XYZ_fixed) (png_const_structrp png_ptr, png_const_inforp info_ptr, png_fixed_point *int_red_X, png_fixed_point *int_red_Y, png_fixed_point *int_red_Z, png_fixed_point *int_green_X, png_fixed_point *int_green_Y, png_fixed_point *int_green_Z, png_fixed_point *int_blue_X, png_fixed_point *int_blue_Y, png_fixed_point *int_blue_Z);
extern void (__cdecl png_set_cHRM) (png_const_structrp png_ptr, png_inforp info_ptr, double white_x, double white_y, double red_x, double red_y, double green_x, double green_y, double blue_x, double blue_y);
extern void (__cdecl png_set_cHRM_XYZ) (png_const_structrp png_ptr, png_inforp info_ptr, double red_X, double red_Y, double red_Z, double green_X, double green_Y, double green_Z, double blue_X, double blue_Y, double blue_Z);
extern void (__cdecl png_set_cHRM_fixed) (png_const_structrp png_ptr, png_inforp info_ptr, png_fixed_point int_white_x, png_fixed_point int_white_y, png_fixed_point int_red_x, png_fixed_point int_red_y, png_fixed_point int_green_x, png_fixed_point int_green_y, png_fixed_point int_blue_x, png_fixed_point int_blue_y);
extern void (__cdecl png_set_cHRM_XYZ_fixed) (png_const_structrp png_ptr, png_inforp info_ptr, png_fixed_point int_red_X, png_fixed_point int_red_Y, png_fixed_point int_red_Z, png_fixed_point int_green_X, png_fixed_point int_green_Y, png_fixed_point int_green_Z, png_fixed_point int_blue_X, png_fixed_point int_blue_Y, png_fixed_point int_blue_Z);
extern png_uint_32 (__cdecl png_get_eXIf) (png_const_structrp png_ptr, png_inforp info_ptr, png_bytep *exif);
extern void (__cdecl png_set_eXIf) (png_const_structrp png_ptr, png_inforp info_ptr, png_bytep exif);
extern png_uint_32 (__cdecl png_get_eXIf_1) (png_const_structrp png_ptr, png_const_inforp info_ptr, png_uint_32 *num_exif, png_bytep *exif);
extern void (__cdecl png_set_eXIf_1) (png_const_structrp png_ptr, png_inforp info_ptr, png_uint_32 num_exif, png_bytep exif);
extern png_uint_32 (__cdecl png_get_gAMA) (png_const_structrp png_ptr, png_const_inforp info_ptr, double *file_gamma);
extern png_uint_32 (__cdecl png_get_gAMA_fixed) (png_const_structrp png_ptr, png_const_inforp info_ptr, png_fixed_point *int_file_gamma);
extern void (__cdecl png_set_gAMA) (png_const_structrp png_ptr, png_inforp info_ptr, double file_gamma);
extern void (__cdecl png_set_gAMA_fixed) (png_const_structrp png_ptr, png_inforp info_ptr, png_fixed_point int_file_gamma);
extern png_uint_32 (__cdecl png_get_hIST) (png_const_structrp png_ptr, png_inforp info_ptr, png_uint_16p *hist);
extern void (__cdecl png_set_hIST) (png_const_structrp png_ptr, png_inforp info_ptr, png_const_uint_16p hist);
extern png_uint_32 (__cdecl png_get_IHDR) (png_const_structrp png_ptr, png_const_inforp info_ptr, png_uint_32 *width, png_uint_32 *height, int *bit_depth, int *color_type, int *interlace_method, int *compression_method, int *filter_method);
extern void (__cdecl png_set_IHDR) (png_const_structrp png_ptr, png_inforp info_ptr, png_uint_32 width, png_uint_32 height, int bit_depth, int color_type, int interlace_method, int compression_method, int filter_method);
extern png_uint_32 (__cdecl png_get_oFFs) (png_const_structrp png_ptr, png_const_inforp info_ptr, png_int_32 *offset_x, png_int_32 *offset_y, int *unit_type);
extern void (__cdecl png_set_oFFs) (png_const_structrp png_ptr, png_inforp info_ptr, png_int_32 offset_x, png_int_32 offset_y, int unit_type);
extern png_uint_32 (__cdecl png_get_pCAL) (png_const_structrp png_ptr, png_inforp info_ptr, png_charp *purpose, png_int_32 *X0, png_int_32 *X1, int * png_uint_32, int *nparams, png_charp *units, png_charpp *params);
extern void (__cdecl png_set_pCAL) (png_const_structrp png_ptr, png_inforp info_ptr, png_const_charp purpose, png_int_32 X0, png_int_32 X1, int type, int nparams, png_const_charp units, png_charpp params);
extern png_uint_32 (__cdecl png_get_pHYs) (png_const_structrp png_ptr, png_const_inforp info_ptr, png_uint_32 *res_x, png_uint_32 *res_y, int *unit_type);
extern void (__cdecl png_set_pHYs) (png_const_structrp png_ptr, png_inforp info_ptr, png_uint_32 res_x, png_uint_32 res_y, int unit_type);
extern png_uint_32 (__cdecl png_get_PLTE) (png_const_structrp png_ptr, png_inforp info_ptr, png_colorp *palette, int *num_palette);
extern void (__cdecl png_set_PLTE) (png_structrp png_ptr, png_inforp info_ptr, png_const_colorp palette, int num_palette);
extern png_uint_32 (__cdecl png_get_sBIT) (png_const_structrp png_ptr, png_inforp info_ptr, png_color_8p *sig_bit);
extern void (__cdecl png_set_sBIT) (png_const_structrp png_ptr, png_inforp info_ptr, png_const_color_8p sig_bit);
extern png_uint_32 (__cdecl png_get_sRGB) (png_const_structrp png_ptr, png_const_inforp info_ptr, int *file_srgb_intent);
extern void (__cdecl png_set_sRGB) (png_const_structrp png_ptr, png_inforp info_ptr, int srgb_intent);
extern void (__cdecl png_set_sRGB_gAMA_and_cHRM) (png_const_structrp png_ptr, png_inforp info_ptr, int srgb_intent);
extern png_uint_32 (__cdecl png_get_iCCP) (png_const_structrp png_ptr, png_inforp info_ptr, png_charpp png_get_iCCP, int *compression_type, png_bytepp profile, png_uint_32 *proflen);
extern void (__cdecl png_set_iCCP) (png_const_structrp png_ptr, png_inforp info_ptr, png_const_charp png_set_iCCP, int compression_type, png_const_bytep profile, png_uint_32 proflen);
extern int (__cdecl png_get_sPLT) (png_const_structrp png_ptr, png_inforp info_ptr, png_sPLT_tpp entries);
extern void (__cdecl png_set_sPLT) (png_const_structrp png_ptr, png_inforp info_ptr, png_const_sPLT_tp entries, int nentries);
extern int (__cdecl png_get_text) (png_const_structrp png_ptr, png_inforp info_ptr, png_textp *text_ptr, int *num_text);
extern void (__cdecl png_set_text) (png_const_structrp png_ptr, png_inforp info_ptr, png_const_textp text_ptr, int num_text);
extern png_uint_32 (__cdecl png_get_tIME) (png_const_structrp png_ptr, png_inforp info_ptr, png_timep *mod_time);
extern void (__cdecl png_set_tIME) (png_const_structrp png_ptr, png_inforp info_ptr, png_const_timep mod_time);
extern png_uint_32 (__cdecl png_get_tRNS) (png_const_structrp png_ptr, png_inforp info_ptr, png_bytep *trans_alpha, int *num_trans, png_color_16p *trans_color);
extern void (__cdecl png_set_tRNS) (png_structrp png_ptr, png_inforp info_ptr, png_const_bytep trans_alpha, int num_trans, png_const_color_16p trans_color);
extern png_uint_32 (__cdecl png_get_sCAL) (png_const_structrp png_ptr, png_const_inforp info_ptr, int *unit, double *width, double *height);
extern png_uint_32 (__cdecl png_get_sCAL_fixed) (png_const_structrp png_ptr, png_const_inforp info_ptr, int *unit, png_fixed_point *width, png_fixed_point *height);
extern png_uint_32 (__cdecl png_get_sCAL_s) (png_const_structrp png_ptr, png_const_inforp info_ptr, int *unit, png_charpp swidth, png_charpp sheight);
extern void (__cdecl png_set_sCAL) (png_const_structrp png_ptr, png_inforp info_ptr, int unit, double width, double height);
extern void (__cdecl png_set_sCAL_fixed) (png_const_structrp png_ptr, png_inforp info_ptr, int unit, png_fixed_point width, png_fixed_point height);
extern void (__cdecl png_set_sCAL_s) (png_const_structrp png_ptr, png_inforp info_ptr, int unit, png_const_charp swidth, png_const_charp sheight);
extern void (__cdecl png_set_keep_unknown_chunks) (png_structrp png_ptr, int keep, png_const_bytep chunk_list, int num_chunks);
extern int (__cdecl png_handle_as_unknown) (png_const_structrp png_ptr, png_const_bytep chunk_name);
extern void (__cdecl png_set_unknown_chunks) (png_const_structrp png_ptr, png_inforp info_ptr, png_const_unknown_chunkp unknowns, int num_unknowns);
extern void (__cdecl png_set_unknown_chunk_location) (png_const_structrp png_ptr, png_inforp info_ptr, int chunk, int location);
extern int (__cdecl png_get_unknown_chunks) (png_const_structrp png_ptr, png_inforp info_ptr, png_unknown_chunkpp entries);
extern void (__cdecl png_set_invalid) (png_const_structrp png_ptr, png_inforp info_ptr, int mask);
extern void (__cdecl png_read_png) (png_structrp png_ptr, png_inforp info_ptr, int transforms, png_voidp params);
extern void (__cdecl png_write_png) (png_structrp png_ptr, png_inforp info_ptr, int transforms, png_voidp params);
extern png_const_charp (__cdecl png_get_copyright) (png_const_structrp png_ptr);
extern png_const_charp (__cdecl png_get_header_ver) (png_const_structrp png_ptr);
extern png_const_charp (__cdecl png_get_header_version) (png_const_structrp png_ptr);
extern png_const_charp (__cdecl png_get_libpng_ver) (png_const_structrp png_ptr);
extern png_uint_32 (__cdecl png_permit_mng_features) (png_structrp png_ptr, png_uint_32 mng_features_permitted);
enum { PNG_HANDLE_CHUNK_AS_DEFAULT = 0 };
enum { PNG_HANDLE_CHUNK_NEVER = 1 };
enum { PNG_HANDLE_CHUNK_IF_SAFE = 2 };
enum { PNG_HANDLE_CHUNK_ALWAYS = 3 };
enum { PNG_HANDLE_CHUNK_LAST = 4 };
extern void (__cdecl png_set_user_limits) (png_structrp png_ptr, png_uint_32 user_width_max, png_uint_32 user_height_max);
extern png_uint_32 (__cdecl png_get_user_width_max) (png_const_structrp png_ptr);
extern png_uint_32 (__cdecl png_get_user_height_max) (png_const_structrp png_ptr);
extern void (__cdecl png_set_chunk_cache_max) (png_structrp png_ptr, png_uint_32 user_chunk_cache_max);
extern png_uint_32 (__cdecl png_get_chunk_cache_max) (png_const_structrp png_ptr);
extern void (__cdecl png_set_chunk_malloc_max) (png_structrp png_ptr, png_alloc_size_t user_chunk_cache_max);
extern png_alloc_size_t (__cdecl png_get_chunk_malloc_max) (png_const_structrp png_ptr);
extern png_uint_32 (__cdecl png_get_pixels_per_inch) (png_const_structrp png_ptr, png_const_inforp info_ptr);
extern png_uint_32 (__cdecl png_get_x_pixels_per_inch) (png_const_structrp png_ptr, png_const_inforp info_ptr);
extern png_uint_32 (__cdecl png_get_y_pixels_per_inch) (png_const_structrp png_ptr, png_const_inforp info_ptr);
extern float (__cdecl png_get_x_offset_inches) (png_const_structrp png_ptr, png_const_inforp info_ptr);
extern png_fixed_point (__cdecl png_get_x_offset_inches_fixed) (png_const_structrp png_ptr, png_const_inforp info_ptr);
extern float (__cdecl png_get_y_offset_inches) (png_const_structrp png_ptr, png_const_inforp info_ptr);
extern png_fixed_point (__cdecl png_get_y_offset_inches_fixed) (png_const_structrp png_ptr, png_const_inforp info_ptr);
extern png_uint_32 (__cdecl png_get_pHYs_dpi) (png_const_structrp png_ptr, png_const_inforp info_ptr, png_uint_32 *res_x, png_uint_32 *res_y, int *unit_type);
extern png_uint_32 (__cdecl png_get_io_state) (png_const_structrp png_ptr);
extern png_uint_32 (__cdecl png_get_io_chunk_type) (png_const_structrp png_ptr);
enum { PNG_IO_NONE = 0 };
enum { PNG_IO_READING = 1 };
enum { PNG_IO_WRITING = 2 };
enum { PNG_IO_SIGNATURE = 16 };
enum { PNG_IO_CHUNK_HDR = 32 };
enum { PNG_IO_CHUNK_DATA = 64 };
enum { PNG_IO_CHUNK_CRC = 128 };
enum { PNG_IO_MASK_OP = 15 };
enum { PNG_IO_MASK_LOC = 240 };
enum { PNG_INTERLACE_ADAM7_PASSES = 7 };
extern png_uint_32 (__cdecl png_get_uint_32) (png_const_bytep buf);
extern png_uint_16 (__cdecl png_get_uint_16) (png_const_bytep buf);
extern png_int_32 (__cdecl png_get_int_32) (png_const_bytep buf);
extern png_uint_32 (__cdecl png_get_uint_31) (png_const_structrp png_ptr, png_const_bytep buf);
extern void (__cdecl png_save_uint_32) (png_bytep buf, png_uint_32 i);
extern void (__cdecl png_save_int_32) (png_bytep buf, png_int_32 i);
extern void (__cdecl png_save_uint_16) (png_bytep buf, unsigned int i);
extern void (__cdecl png_set_check_for_invalid_index) (png_structrp png_ptr, int allowed);
extern int (__cdecl png_get_palette_max) (png_const_structp png_ptr, png_const_infop info_ptr);
enum { PNG_IMAGE_VERSION = 1 };
typedef struct png_control *png_controlp;
typedef struct {
	png_controlp opaque;
	png_uint_32 version;
	png_uint_32 width;
	png_uint_32 height;
	png_uint_32 format;
	png_uint_32 flags;
	png_uint_32 colormap_entries;
	enum { PNG_IMAGE_WARNING = 1 };
	enum { PNG_IMAGE_ERROR = 2 };
	png_uint_32 warning_or_error;
	char message[64];
} png_image, *png_imagep;
enum { PNG_FORMAT_FLAG_ALPHA = 1 };
enum { PNG_FORMAT_FLAG_COLOR = 2 };
enum { PNG_FORMAT_FLAG_LINEAR = 4 };
enum { PNG_FORMAT_FLAG_COLORMAP = 8 };
enum { PNG_FORMAT_FLAG_BGR = 16 };
enum { PNG_FORMAT_FLAG_AFIRST = 32 };
enum { PNG_FORMAT_FLAG_ASSOCIATED_ALPHA = 64 };
enum { PNG_FORMAT_GRAY = 0 };
enum { PNG_FORMAT_GA = 1 };
enum { PNG_FORMAT_AG = 33 };
enum { PNG_FORMAT_RGB = 2 };
enum { PNG_FORMAT_BGR = 18 };
enum { PNG_FORMAT_RGBA = 3 };
enum { PNG_FORMAT_ARGB = 35 };
enum { PNG_FORMAT_BGRA = 19 };
enum { PNG_FORMAT_ABGR = 51 };
enum { PNG_FORMAT_LINEAR_Y = 4 };
enum { PNG_FORMAT_LINEAR_Y_ALPHA = 5 };
enum { PNG_FORMAT_LINEAR_RGB = 6 };
enum { PNG_FORMAT_LINEAR_RGB_ALPHA = 7 };
enum { PNG_FORMAT_RGB_COLORMAP = 10 };
enum { PNG_FORMAT_BGR_COLORMAP = 26 };
enum { PNG_FORMAT_RGBA_COLORMAP = 11 };
enum { PNG_FORMAT_ARGB_COLORMAP = 43 };
enum { PNG_FORMAT_BGRA_COLORMAP = 27 };
enum { PNG_FORMAT_ABGR_COLORMAP = 59 };
enum { PNG_IMAGE_FLAG_COLORSPACE_NOT_sRGB = 1 };
enum { PNG_IMAGE_FLAG_FAST = 2 };
enum { PNG_IMAGE_FLAG_16BIT_sRGB = 4 };
extern int (__cdecl png_image_begin_read_from_file) (png_imagep image, const char *file_name);
extern int (__cdecl png_image_begin_read_from_stdio) (png_imagep image, FILE* file);
extern int (__cdecl png_image_begin_read_from_memory) (png_imagep image, png_const_voidp memory, size_t size);
extern int (__cdecl png_image_finish_read) (png_imagep image, png_const_colorp background, void *buffer, png_int_32 row_stride, void *colormap);
extern void (__cdecl png_image_free) (png_imagep image);
extern int (__cdecl png_image_write_to_file) (png_imagep image, const char *file, int convert_to_8bit, const void *buffer, png_int_32 row_stride, const void *colormap);
extern int (__cdecl png_image_write_to_stdio) (png_imagep image, FILE *file, int convert_to_8_bit, const void *buffer, png_int_32 row_stride, const void *colormap);
extern int (__cdecl png_image_write_to_memory) (png_imagep image, void *memory, png_alloc_size_t * memory_bytes, int convert_to_8_bit, const void *buffer, png_int_32 row_stride, const void *colormap);
enum { PNG_MAXIMUM_INFLATE_WINDOW = 2 };
enum { PNG_SKIP_sRGB_CHECK_PROFILE = 4 };
enum { PNG_IGNORE_ADLER32 = 8 };
enum { PNG_OPTION_NEXT = 12 };
enum { PNG_OPTION_UNSET = 0 };
enum { PNG_OPTION_INVALID = 1 };
enum { PNG_OPTION_OFF = 2 };
enum { PNG_OPTION_ON = 3 };
extern int (__cdecl png_set_option) (png_structrp png_ptr, int option, int onoff);
/* + END   C:/Users/Chris/include/png.h */
]]
return require 'ffi.load' 'libpng16'
