local ffi = require 'ffi'
ffi.cdef[[
/* BEGIN /usr/include/fitsio.h */
enum { _FITSIO_H = 1 };
/* #define CFITSIO_VERSION 4.0.0 ### string, not number "4.0.0" */
enum { CFITSIO_MICRO = 0 };
enum { CFITSIO_MINOR = 0 };
enum { CFITSIO_MAJOR = 4 };
enum { CFITSIO_SONAME = 9 };
enum { CFITS_API = 1 };
/* BEGIN /usr/include/stdio.h */
]] require 'ffi.c.stdio' ffi.cdef[[
/* END /usr/include/stdio.h */
/* BEGIN /usr/include/x86_64-linux-gnu/sys/types.h */
]] require 'ffi.c.sys.types' ffi.cdef[[
/* END /usr/include/x86_64-1-gnu/sys/types.h */
/* BEGIN /usr/include/c++/11/stdlib.h */
]] require 'ffi.c.stdlib' ffi.cdef[[
/* END /usr/include/c++/11/stdlib.h */
/* BEGIN /usr/lib/gcc/x86_64-linux-gnu/11/include/limits.h */
]] require 'ffi.c.limits' ffi.cdef[[
/* END /usr/lib/gcc/x86_64-1-gnu/11/include/limits.h */
enum { OFF_T = 0 };
enum { USE_LL_SUFFIX = 1 };
typedef long long LONGLONG;
typedef unsigned long long ULONGLONG;
enum { LONGLONG_TYPE = 1 };
/* #define LONGLONG_MAX LLONG_MAX ### string, not number "LLONG_MAX" */
/* #define LONGLONG_MIN LLONG_MIN ### string, not number "LLONG_MIN" */
/* BEGIN /usr/include/longnam.h */
enum { _LONGNAME_H = 1 };
enum { fits_parse_input_url = 0 };
enum { fits_parse_input_filename = 0 };
enum { fits_parse_rootname = 0 };
enum { fits_file_exists = 0 };
enum { fits_parse_output_url = 0 };
enum { fits_parse_extspec = 0 };
enum { fits_parse_extnum = 0 };
enum { fits_parse_binspec = 0 };
enum { fits_parse_binrange = 0 };
enum { fits_parse_range = 0 };
enum { fits_parse_rangell = 0 };
enum { fits_open_memfile = 0 };
enum { fits_open_data = 0 };
enum { fits_open_extlist = 0 };
enum { fits_open_table = 0 };
enum { fits_open_image = 0 };
enum { fits_open_diskfile = 0 };
enum { fits_reopen_file = 0 };
enum { fits_create_file = 0 };
enum { fits_create_diskfile = 0 };
enum { fits_create_memfile = 0 };
enum { fits_create_template = 0 };
enum { fits_flush_file = 0 };
enum { fits_flush_buffer = 0 };
enum { fits_close_file = 0 };
enum { fits_delete_file = 0 };
enum { fits_file_name = 0 };
enum { fits_file_mode = 0 };
enum { fits_url_type = 0 };
enum { fits_get_version = 0 };
enum { fits_uppercase = 0 };
enum { fits_get_errstatus = 0 };
enum { fits_write_errmsg = 0 };
enum { fits_write_errmark = 0 };
enum { fits_read_errmsg = 0 };
enum { fits_clear_errmsg = 0 };
enum { fits_clear_errmark = 0 };
enum { fits_report_error = 0 };
enum { fits_compare_str = 0 };
enum { fits_test_keyword = 0 };
enum { fits_test_record = 0 };
enum { fits_null_check = 0 };
enum { fits_make_keyn = 0 };
enum { fits_make_nkey = 0 };
enum { fits_make_key = 0 };
enum { fits_get_keyclass = 0 };
enum { fits_get_keytype = 0 };
enum { fits_get_inttype = 0 };
enum { fits_parse_value = 0 };
enum { fits_get_keyname = 0 };
enum { fits_parse_template = 0 };
enum { fits_ascii_tform = 0 };
enum { fits_binary_tform = 0 };
enum { fits_binary_tformll = 0 };
enum { fits_get_tbcol = 0 };
enum { fits_get_rowsize = 0 };
enum { fits_get_col_display_width = 0 };
enum { fits_write_record = 0 };
enum { fits_write_key = 0 };
enum { fits_write_key_unit = 0 };
enum { fits_write_comment = 0 };
enum { fits_write_history = 0 };
enum { fits_write_date = 0 };
enum { fits_get_system_time = 0 };
enum { fits_get_system_date = 0 };
enum { fits_date2str = 0 };
enum { fits_time2str = 0 };
enum { fits_str2date = 0 };
enum { fits_str2time = 0 };
enum { fits_write_key_longstr = 0 };
enum { fits_write_key_longwarn = 0 };
enum { fits_write_key_null = 0 };
enum { fits_write_key_str = 0 };
enum { fits_write_key_log = 0 };
enum { fits_write_key_lng = 0 };
enum { fits_write_key_ulng = 0 };
enum { fits_write_key_fixflt = 0 };
enum { fits_write_key_flt = 0 };
enum { fits_write_key_fixdbl = 0 };
enum { fits_write_key_dbl = 0 };
enum { fits_write_key_fixcmp = 0 };
enum { fits_write_key_cmp = 0 };
enum { fits_write_key_fixdblcmp = 0 };
enum { fits_write_key_dblcmp = 0 };
enum { fits_write_key_triple = 0 };
enum { fits_write_tdim = 0 };
enum { fits_write_tdimll = 0 };
enum { fits_write_keys_str = 0 };
enum { fits_write_keys_log = 0 };
enum { fits_write_keys_lng = 0 };
enum { fits_write_keys_fixflt = 0 };
enum { fits_write_keys_flt = 0 };
enum { fits_write_keys_fixdbl = 0 };
enum { fits_write_keys_dbl = 0 };
enum { fits_copy_key = 0 };
enum { fits_write_imghdr = 0 };
enum { fits_write_imghdrll = 0 };
enum { fits_write_grphdr = 0 };
enum { fits_write_grphdrll = 0 };
enum { fits_write_atblhdr = 0 };
enum { fits_write_btblhdr = 0 };
enum { fits_write_exthdr = 0 };
enum { fits_write_key_template = 0 };
enum { fits_get_hdrspace = 0 };
enum { fits_get_hdrpos = 0 };
enum { fits_movabs_key = 0 };
enum { fits_movrel_key = 0 };
enum { fits_find_nextkey = 0 };
enum { fits_read_record = 0 };
enum { fits_read_card = 0 };
enum { fits_read_str = 0 };
enum { fits_read_key_unit = 0 };
enum { fits_read_keyn = 0 };
enum { fits_read_key = 0 };
enum { fits_read_keyword = 0 };
enum { fits_read_key_str = 0 };
enum { fits_read_key_log = 0 };
enum { fits_read_key_lng = 0 };
enum { fits_read_key_lnglng = 0 };
enum { fits_read_key_ulnglng = 0 };
enum { fits_read_key_flt = 0 };
enum { fits_read_key_dbl = 0 };
enum { fits_read_key_cmp = 0 };
enum { fits_read_key_dblcmp = 0 };
enum { fits_read_key_triple = 0 };
enum { fits_get_key_strlen = 0 };
enum { fits_read_key_longstr = 0 };
enum { fits_read_string_key = 0 };
enum { fits_free_memory = 0 };
enum { fits_read_tdim = 0 };
enum { fits_read_tdimll = 0 };
enum { fits_decode_tdim = 0 };
enum { fits_decode_tdimll = 0 };
enum { fits_read_keys_str = 0 };
enum { fits_read_keys_log = 0 };
enum { fits_read_keys_lng = 0 };
enum { fits_read_keys_lnglng = 0 };
enum { fits_read_keys_flt = 0 };
enum { fits_read_keys_dbl = 0 };
enum { fits_read_imghdr = 0 };
enum { fits_read_imghdrll = 0 };
enum { fits_read_atblhdr = 0 };
enum { fits_read_btblhdr = 0 };
enum { fits_read_atblhdrll = 0 };
enum { fits_read_btblhdrll = 0 };
enum { fits_hdr2str = 0 };
enum { fits_convert_hdr2str = 0 };
enum { fits_update_card = 0 };
enum { fits_update_key = 0 };
enum { fits_update_key_null = 0 };
enum { fits_update_key_str = 0 };
enum { fits_update_key_longstr = 0 };
enum { fits_update_key_log = 0 };
enum { fits_update_key_lng = 0 };
enum { fits_update_key_fixflt = 0 };
enum { fits_update_key_flt = 0 };
enum { fits_update_key_fixdbl = 0 };
enum { fits_update_key_dbl = 0 };
enum { fits_update_key_fixcmp = 0 };
enum { fits_update_key_cmp = 0 };
enum { fits_update_key_fixdblcmp = 0 };
enum { fits_update_key_dblcmp = 0 };
enum { fits_modify_record = 0 };
enum { fits_modify_card = 0 };
enum { fits_modify_name = 0 };
enum { fits_modify_comment = 0 };
enum { fits_modify_key_null = 0 };
enum { fits_modify_key_str = 0 };
enum { fits_modify_key_longstr = 0 };
enum { fits_modify_key_log = 0 };
enum { fits_modify_key_lng = 0 };
enum { fits_modify_key_fixflt = 0 };
enum { fits_modify_key_flt = 0 };
enum { fits_modify_key_fixdbl = 0 };
enum { fits_modify_key_dbl = 0 };
enum { fits_modify_key_fixcmp = 0 };
enum { fits_modify_key_cmp = 0 };
enum { fits_modify_key_fixdblcmp = 0 };
enum { fits_modify_key_dblcmp = 0 };
enum { fits_insert_record = 0 };
enum { fits_insert_card = 0 };
enum { fits_insert_key_null = 0 };
enum { fits_insert_key_str = 0 };
enum { fits_insert_key_longstr = 0 };
enum { fits_insert_key_log = 0 };
enum { fits_insert_key_lng = 0 };
enum { fits_insert_key_fixflt = 0 };
enum { fits_insert_key_flt = 0 };
enum { fits_insert_key_fixdbl = 0 };
enum { fits_insert_key_dbl = 0 };
enum { fits_insert_key_fixcmp = 0 };
enum { fits_insert_key_cmp = 0 };
enum { fits_insert_key_fixdblcmp = 0 };
enum { fits_insert_key_dblcmp = 0 };
enum { fits_delete_key = 0 };
enum { fits_delete_str = 0 };
enum { fits_delete_record = 0 };
enum { fits_get_hdu_num = 0 };
enum { fits_get_hdu_type = 0 };
enum { fits_get_hduaddr = 0 };
enum { fits_get_hduaddrll = 0 };
enum { fits_get_hduoff = 0 };
enum { fits_get_img_param = 0 };
enum { fits_get_img_paramll = 0 };
enum { fits_get_img_type = 0 };
enum { fits_get_img_equivtype = 0 };
enum { fits_get_img_dim = 0 };
enum { fits_get_img_size = 0 };
enum { fits_get_img_sizell = 0 };
enum { fits_movabs_hdu = 0 };
enum { fits_movrel_hdu = 0 };
enum { fits_movnam_hdu = 0 };
enum { fits_get_num_hdus = 0 };
enum { fits_create_img = 0 };
enum { fits_create_imgll = 0 };
enum { fits_create_tbl = 0 };
enum { fits_create_hdu = 0 };
enum { fits_insert_img = 0 };
enum { fits_insert_imgll = 0 };
enum { fits_insert_atbl = 0 };
enum { fits_insert_btbl = 0 };
enum { fits_resize_img = 0 };
enum { fits_resize_imgll = 0 };
enum { fits_delete_hdu = 0 };
enum { fits_copy_hdu = 0 };
enum { fits_copy_file = 0 };
enum { fits_copy_header = 0 };
enum { fits_copy_hdutab = 0 };
enum { fits_copy_data = 0 };
enum { fits_write_hdu = 0 };
enum { fits_set_hdustruc = 0 };
enum { fits_set_hdrsize = 0 };
enum { fits_write_theap = 0 };
enum { fits_encode_chksum = 0 };
enum { fits_decode_chksum = 0 };
enum { fits_write_chksum = 0 };
enum { fits_update_chksum = 0 };
enum { fits_verify_chksum = 0 };
enum { fits_get_chksum = 0 };
enum { fits_set_bscale = 0 };
enum { fits_set_tscale = 0 };
enum { fits_set_imgnull = 0 };
enum { fits_set_btblnull = 0 };
enum { fits_set_atblnull = 0 };
enum { fits_get_colnum = 0 };
enum { fits_get_colname = 0 };
enum { fits_get_coltype = 0 };
enum { fits_get_coltypell = 0 };
enum { fits_get_eqcoltype = 0 };
enum { fits_get_eqcoltypell = 0 };
enum { fits_get_num_rows = 0 };
enum { fits_get_num_rowsll = 0 };
enum { fits_get_num_cols = 0 };
enum { fits_get_acolparms = 0 };
enum { fits_get_bcolparms = 0 };
enum { fits_get_bcolparmsll = 0 };
enum { fits_iterate_data = 0 };
enum { fits_read_grppar_byt = 0 };
enum { fits_read_grppar_sbyt = 0 };
enum { fits_read_grppar_usht = 0 };
enum { fits_read_grppar_ulng = 0 };
enum { fits_read_grppar_ulnglng = 0 };
enum { fits_read_grppar_sht = 0 };
enum { fits_read_grppar_lng = 0 };
enum { fits_read_grppar_lnglng = 0 };
enum { fits_read_grppar_int = 0 };
enum { fits_read_grppar_uint = 0 };
enum { fits_read_grppar_flt = 0 };
enum { fits_read_grppar_dbl = 0 };
enum { fits_read_pix = 0 };
enum { fits_read_pixll = 0 };
enum { fits_read_pixnull = 0 };
enum { fits_read_pixnullll = 0 };
enum { fits_read_img = 0 };
enum { fits_read_imgnull = 0 };
enum { fits_read_img_byt = 0 };
enum { fits_read_img_sbyt = 0 };
enum { fits_read_img_usht = 0 };
enum { fits_read_img_ulng = 0 };
enum { fits_read_img_sht = 0 };
enum { fits_read_img_lng = 0 };
enum { fits_read_img_ulnglng = 0 };
enum { fits_read_img_lnglng = 0 };
enum { fits_read_img_uint = 0 };
enum { fits_read_img_int = 0 };
enum { fits_read_img_flt = 0 };
enum { fits_read_img_dbl = 0 };
enum { fits_read_imgnull_byt = 0 };
enum { fits_read_imgnull_sbyt = 0 };
enum { fits_read_imgnull_usht = 0 };
enum { fits_read_imgnull_ulng = 0 };
enum { fits_read_imgnull_sht = 0 };
enum { fits_read_imgnull_lng = 0 };
enum { fits_read_imgnull_ulnglng = 0 };
enum { fits_read_imgnull_lnglng = 0 };
enum { fits_read_imgnull_uint = 0 };
enum { fits_read_imgnull_int = 0 };
enum { fits_read_imgnull_flt = 0 };
enum { fits_read_imgnull_dbl = 0 };
enum { fits_read_2d_byt = 0 };
enum { fits_read_2d_sbyt = 0 };
enum { fits_read_2d_usht = 0 };
enum { fits_read_2d_ulng = 0 };
enum { fits_read_2d_sht = 0 };
enum { fits_read_2d_lng = 0 };
enum { fits_read_2d_ulnglng = 0 };
enum { fits_read_2d_lnglng = 0 };
enum { fits_read_2d_uint = 0 };
enum { fits_read_2d_int = 0 };
enum { fits_read_2d_flt = 0 };
enum { fits_read_2d_dbl = 0 };
enum { fits_read_3d_byt = 0 };
enum { fits_read_3d_sbyt = 0 };
enum { fits_read_3d_usht = 0 };
enum { fits_read_3d_ulng = 0 };
enum { fits_read_3d_sht = 0 };
enum { fits_read_3d_lng = 0 };
enum { fits_read_3d_ulnglng = 0 };
enum { fits_read_3d_lnglng = 0 };
enum { fits_read_3d_uint = 0 };
enum { fits_read_3d_int = 0 };
enum { fits_read_3d_flt = 0 };
enum { fits_read_3d_dbl = 0 };
enum { fits_read_subset = 0 };
enum { fits_read_subset_byt = 0 };
enum { fits_read_subset_sbyt = 0 };
enum { fits_read_subset_usht = 0 };
enum { fits_read_subset_ulng = 0 };
enum { fits_read_subset_sht = 0 };
enum { fits_read_subset_lng = 0 };
enum { fits_read_subset_ulnglng = 0 };
enum { fits_read_subset_lnglng = 0 };
enum { fits_read_subset_uint = 0 };
enum { fits_read_subset_int = 0 };
enum { fits_read_subset_flt = 0 };
enum { fits_read_subset_dbl = 0 };
enum { fits_read_subsetnull_byt = 0 };
enum { fits_read_subsetnull_sbyt = 0 };
enum { fits_read_subsetnull_usht = 0 };
enum { fits_read_subsetnull_ulng = 0 };
enum { fits_read_subsetnull_sht = 0 };
enum { fits_read_subsetnull_lng = 0 };
enum { fits_read_subsetnull_ulnglng = 0 };
enum { fits_read_subsetnull_lnglng = 0 };
enum { fits_read_subsetnull_uint = 0 };
enum { fits_read_subsetnull_int = 0 };
enum { fits_read_subsetnull_flt = 0 };
enum { fits_read_subsetnull_dbl = 0 };
enum { ffcpimg = 0 };
enum { fits_compress_img = 0 };
enum { fits_decompress_img = 0 };
enum { fits_read_col = 0 };
enum { fits_read_colnull = 0 };
enum { fits_read_col_str = 0 };
enum { fits_read_col_log = 0 };
enum { fits_read_col_byt = 0 };
enum { fits_read_col_sbyt = 0 };
enum { fits_read_col_usht = 0 };
enum { fits_read_col_ulng = 0 };
enum { fits_read_col_sht = 0 };
enum { fits_read_col_lng = 0 };
enum { fits_read_col_ulnglng = 0 };
enum { fits_read_col_lnglng = 0 };
enum { fits_read_col_uint = 0 };
enum { fits_read_col_int = 0 };
enum { fits_read_col_flt = 0 };
enum { fits_read_col_dbl = 0 };
enum { fits_read_col_cmp = 0 };
enum { fits_read_col_dblcmp = 0 };
enum { fits_read_col_bit = 0 };
enum { fits_read_col_bit_usht = 0 };
enum { fits_read_col_bit_uint = 0 };
enum { fits_read_colnull_str = 0 };
enum { fits_read_colnull_log = 0 };
enum { fits_read_colnull_byt = 0 };
enum { fits_read_colnull_sbyt = 0 };
enum { fits_read_colnull_usht = 0 };
enum { fits_read_colnull_ulng = 0 };
enum { fits_read_colnull_sht = 0 };
enum { fits_read_colnull_lng = 0 };
enum { fits_read_colnull_ulnglng = 0 };
enum { fits_read_colnull_lnglng = 0 };
enum { fits_read_colnull_uint = 0 };
enum { fits_read_colnull_int = 0 };
enum { fits_read_colnull_flt = 0 };
enum { fits_read_colnull_dbl = 0 };
enum { fits_read_colnull_cmp = 0 };
enum { fits_read_colnull_dblcmp = 0 };
enum { fits_read_descript = 0 };
enum { fits_read_descriptll = 0 };
enum { fits_read_descripts = 0 };
enum { fits_read_descriptsll = 0 };
enum { fits_read_tblbytes = 0 };
enum { fits_write_grppar_byt = 0 };
enum { fits_write_grppar_sbyt = 0 };
enum { fits_write_grppar_usht = 0 };
enum { fits_write_grppar_ulng = 0 };
enum { fits_write_grppar_sht = 0 };
enum { fits_write_grppar_lng = 0 };
enum { fits_write_grppar_ulnglng = 0 };
enum { fits_write_grppar_lnglng = 0 };
enum { fits_write_grppar_uint = 0 };
enum { fits_write_grppar_int = 0 };
enum { fits_write_grppar_flt = 0 };
enum { fits_write_grppar_dbl = 0 };
enum { fits_write_pix = 0 };
enum { fits_write_pixll = 0 };
enum { fits_write_pixnull = 0 };
enum { fits_write_pixnullll = 0 };
enum { fits_write_img = 0 };
enum { fits_write_img_byt = 0 };
enum { fits_write_img_sbyt = 0 };
enum { fits_write_img_usht = 0 };
enum { fits_write_img_ulng = 0 };
enum { fits_write_img_sht = 0 };
enum { fits_write_img_lng = 0 };
enum { fits_write_img_ulnglng = 0 };
enum { fits_write_img_lnglng = 0 };
enum { fits_write_img_uint = 0 };
enum { fits_write_img_int = 0 };
enum { fits_write_img_flt = 0 };
enum { fits_write_img_dbl = 0 };
enum { fits_write_imgnull = 0 };
enum { fits_write_imgnull_byt = 0 };
enum { fits_write_imgnull_sbyt = 0 };
enum { fits_write_imgnull_usht = 0 };
enum { fits_write_imgnull_ulng = 0 };
enum { fits_write_imgnull_sht = 0 };
enum { fits_write_imgnull_lng = 0 };
enum { fits_write_imgnull_ulnglng = 0 };
enum { fits_write_imgnull_lnglng = 0 };
enum { fits_write_imgnull_uint = 0 };
enum { fits_write_imgnull_int = 0 };
enum { fits_write_imgnull_flt = 0 };
enum { fits_write_imgnull_dbl = 0 };
enum { fits_write_img_null = 0 };
enum { fits_write_null_img = 0 };
enum { fits_write_2d_byt = 0 };
enum { fits_write_2d_sbyt = 0 };
enum { fits_write_2d_usht = 0 };
enum { fits_write_2d_ulng = 0 };
enum { fits_write_2d_sht = 0 };
enum { fits_write_2d_lng = 0 };
enum { fits_write_2d_ulnglng = 0 };
enum { fits_write_2d_lnglng = 0 };
enum { fits_write_2d_uint = 0 };
enum { fits_write_2d_int = 0 };
enum { fits_write_2d_flt = 0 };
enum { fits_write_2d_dbl = 0 };
enum { fits_write_3d_byt = 0 };
enum { fits_write_3d_sbyt = 0 };
enum { fits_write_3d_usht = 0 };
enum { fits_write_3d_ulng = 0 };
enum { fits_write_3d_sht = 0 };
enum { fits_write_3d_lng = 0 };
enum { fits_write_3d_ulnglng = 0 };
enum { fits_write_3d_lnglng = 0 };
enum { fits_write_3d_uint = 0 };
enum { fits_write_3d_int = 0 };
enum { fits_write_3d_flt = 0 };
enum { fits_write_3d_dbl = 0 };
enum { fits_write_subset = 0 };
enum { fits_write_subset_byt = 0 };
enum { fits_write_subset_sbyt = 0 };
enum { fits_write_subset_usht = 0 };
enum { fits_write_subset_ulng = 0 };
enum { fits_write_subset_sht = 0 };
enum { fits_write_subset_lng = 0 };
enum { fits_write_subset_ulnglng = 0 };
enum { fits_write_subset_lnglng = 0 };
enum { fits_write_subset_uint = 0 };
enum { fits_write_subset_int = 0 };
enum { fits_write_subset_flt = 0 };
enum { fits_write_subset_dbl = 0 };
enum { fits_write_col = 0 };
enum { fits_write_col_str = 0 };
enum { fits_write_col_log = 0 };
enum { fits_write_col_byt = 0 };
enum { fits_write_col_sbyt = 0 };
enum { fits_write_col_usht = 0 };
enum { fits_write_col_ulng = 0 };
enum { fits_write_col_sht = 0 };
enum { fits_write_col_lng = 0 };
enum { fits_write_col_ulnglng = 0 };
enum { fits_write_col_lnglng = 0 };
enum { fits_write_col_uint = 0 };
enum { fits_write_col_int = 0 };
enum { fits_write_col_flt = 0 };
enum { fits_write_col_dbl = 0 };
enum { fits_write_col_cmp = 0 };
enum { fits_write_col_dblcmp = 0 };
enum { fits_write_col_null = 0 };
enum { fits_write_col_bit = 0 };
enum { fits_write_nulrows = 0 };
enum { fits_write_nullrows = 0 };
enum { fits_write_colnull = 0 };
enum { fits_write_colnull_str = 0 };
enum { fits_write_colnull_log = 0 };
enum { fits_write_colnull_byt = 0 };
enum { fits_write_colnull_sbyt = 0 };
enum { fits_write_colnull_usht = 0 };
enum { fits_write_colnull_ulng = 0 };
enum { fits_write_colnull_sht = 0 };
enum { fits_write_colnull_lng = 0 };
enum { fits_write_colnull_ulnglng = 0 };
enum { fits_write_colnull_lnglng = 0 };
enum { fits_write_colnull_uint = 0 };
enum { fits_write_colnull_int = 0 };
enum { fits_write_colnull_flt = 0 };
enum { fits_write_colnull_dbl = 0 };
enum { fits_write_ext = 0 };
enum { fits_read_ext = 0 };
enum { fits_write_descript = 0 };
enum { fits_compress_heap = 0 };
enum { fits_test_heap = 0 };
enum { fits_write_tblbytes = 0 };
enum { fits_insert_rows = 0 };
enum { fits_delete_rows = 0 };
enum { fits_delete_rowrange = 0 };
enum { fits_delete_rowlist = 0 };
enum { fits_delete_rowlistll = 0 };
enum { fits_insert_col = 0 };
enum { fits_insert_cols = 0 };
enum { fits_delete_col = 0 };
enum { fits_copy_col = 0 };
enum { fits_copy_cols = 0 };
enum { fits_copy_rows = 0 };
enum { fits_modify_vector_len = 0 };
enum { fits_read_img_coord = 0 };
enum { fits_read_img_coord_version = 0 };
enum { fits_read_tbl_coord = 0 };
enum { fits_pix_to_world = 0 };
enum { fits_world_to_pix = 0 };
enum { fits_get_image_wcs_keys = 0 };
enum { fits_get_table_wcs_keys = 0 };
enum { fits_find_rows = 0 };
enum { fits_find_first_row = 0 };
enum { fits_find_rows_cmp = 0 };
enum { fits_select_rows = 0 };
enum { fits_calc_rows = 0 };
enum { fits_calculator = 0 };
enum { fits_calculator_rng = 0 };
enum { fits_test_expr = 0 };
enum { fits_create_group = 0 };
enum { fits_insert_group = 0 };
enum { fits_change_group = 0 };
enum { fits_remove_group = 0 };
enum { fits_copy_group = 0 };
enum { fits_merge_groups = 0 };
enum { fits_compact_group = 0 };
enum { fits_verify_group = 0 };
enum { fits_open_group = 0 };
enum { fits_add_group_member = 0 };
enum { fits_get_num_members = 0 };
enum { fits_get_num_groups = 0 };
enum { fits_open_member = 0 };
enum { fits_copy_member = 0 };
enum { fits_transfer_member = 0 };
enum { fits_remove_member = 0 };
enum { fits_init_https = 0 };
enum { fits_cleanup_https = 0 };
enum { fits_verbose_https = 0 };
enum { fits_show_download_progress = 0 };
enum { fits_get_timeout = 0 };
enum { fits_set_timeout = 0 };
/* END /usr/include/longnam.h */
enum { NIOBUF = 40 };
enum { IOBUFLEN = 2880 };
enum { FLEN_FILENAME = 1025 };
enum { FLEN_KEYWORD = 75 };
enum { FLEN_CARD = 81 };
enum { FLEN_VALUE = 71 };
enum { FLEN_COMMENT = 73 };
enum { FLEN_ERRMSG = 81 };
enum { FLEN_STATUS = 31 };
enum { TBIT = 1 };
enum { TBYTE = 11 };
enum { TSBYTE = 12 };
enum { TLOGICAL = 14 };
enum { TSTRING = 16 };
enum { TUSHORT = 20 };
enum { TSHORT = 21 };
enum { TUINT = 30 };
enum { TINT = 31 };
enum { TULONG = 40 };
enum { TLONG = 41 };
enum { TINT32BIT = 41 };
enum { TFLOAT = 42 };
enum { TULONGLONG = 80 };
enum { TLONGLONG = 81 };
enum { TDOUBLE = 82 };
enum { TCOMPLEX = 83 };
enum { TDBLCOMPLEX = 163 };
enum { TYP_STRUC_KEY = 10 };
enum { TYP_CMPRS_KEY = 20 };
enum { TYP_SCAL_KEY = 30 };
enum { TYP_NULL_KEY = 40 };
enum { TYP_DIM_KEY = 50 };
enum { TYP_RANG_KEY = 60 };
enum { TYP_UNIT_KEY = 70 };
enum { TYP_DISP_KEY = 80 };
enum { TYP_HDUID_KEY = 90 };
enum { TYP_CKSUM_KEY = 100 };
enum { TYP_WCS_KEY = 110 };
enum { TYP_REFSYS_KEY = 120 };
enum { TYP_COMM_KEY = 130 };
enum { TYP_CONT_KEY = 140 };
enum { TYP_USER_KEY = 150 };
enum { INT32BIT = 0 };
enum { BYTE_IMG = 8 };
enum { SHORT_IMG = 16 };
enum { LONG_IMG = 32 };
enum { LONGLONG_IMG = 64 };
enum { FLOAT_IMG = -32 };
enum { DOUBLE_IMG = -64 };
enum { SBYTE_IMG = 10 };
enum { USHORT_IMG = 20 };
enum { ULONG_IMG = 40 };
enum { ULONGLONG_IMG = 80 };
enum { IMAGE_HDU = 0 };
enum { ASCII_TBL = 1 };
enum { BINARY_TBL = 2 };
enum { ANY_HDU = -1 };
enum { READONLY = 0 };
enum { READWRITE = 1 };
/* #define FLOATNULLVALUE -9.11912E-36F ### string, not number "-9.11912E-36F" */
/* #define DOUBLENULLVALUE -9.1191291391491E-36 ### string, number, replaceline "-9.1191291391491E-36" */
enum { NO_DITHER = -1 };
enum { SUBTRACTIVE_DITHER_1 = 1 };
enum { SUBTRACTIVE_DITHER_2 = 2 };
enum { MAX_COMPRESS_DIM = 6 };
enum { RICE_1 = 11 };
enum { GZIP_1 = 21 };
enum { GZIP_2 = 22 };
enum { PLIO_1 = 31 };
enum { HCOMPRESS_1 = 41 };
enum { BZIP2_1 = 51 };
enum { NOCOMPRESS = -1 };
enum { TRUE = 1 };
enum { FALSE = 0 };
enum { CASESEN = 1 };
enum { CASEINSEN = 0 };
enum { GT_ID_ALL_URI = 0 };
enum { GT_ID_REF = 1 };
enum { GT_ID_POS = 2 };
enum { GT_ID_ALL = 3 };
enum { GT_ID_REF_URI = 11 };
enum { GT_ID_POS_URI = 12 };
enum { OPT_RM_GPT = 0 };
enum { OPT_RM_ENTRY = 1 };
enum { OPT_RM_MBR = 2 };
enum { OPT_RM_ALL = 3 };
enum { OPT_GCP_GPT = 0 };
enum { OPT_GCP_MBR = 1 };
enum { OPT_GCP_ALL = 2 };
enum { OPT_MCP_ADD = 0 };
enum { OPT_MCP_NADD = 1 };
enum { OPT_MCP_REPL = 2 };
enum { OPT_MCP_MOV = 3 };
enum { OPT_MRG_COPY = 0 };
enum { OPT_MRG_MOV = 1 };
enum { OPT_CMT_MBR = 1 };
enum { OPT_CMT_MBR_DEL = 11 };
typedef struct { char ttype[70];
LONGLONG tbcol;
int tdatatype;
LONGLONG trepeat;
double tscale;
double tzero;
LONGLONG tnull;
char strnull[20];
char tform[10];
long twidth;
}tcolumn;
enum { VALIDSTRUC = 555 };
typedef struct { int filehandle;
int driver;
int open_count;
char *filename;
int validcode;
int only_one;
int noextsyntax;
LONGLONG filesize;
LONGLONG logfilesize;
int lasthdu;
LONGLONG bytepos;
LONGLONG io_pos;
int curbuf;
int curhdu;
int hdutype;
int writemode;
int maxhdu;
int MAXHDU;
LONGLONG *headstart;
LONGLONG headend;
LONGLONG ENDpos;
LONGLONG nextkey;
LONGLONG datastart;
int imgdim;
LONGLONG imgnaxis[99];
int tfield;
int startcol;
LONGLONG origrows;
LONGLONG numrows;
LONGLONG rowlength;
tcolumn *tableptr;
LONGLONG heapstart;
LONGLONG heapsize;
int request_compress_type;
long request_tilesize[6];
float request_quantize_level;
int request_quantize_method;
int request_dither_seed;
int request_lossy_int_compress;
int request_huge_hdu;
float request_hcomp_scale;
int request_hcomp_smooth;
int compress_type;
long tilesize[6];
float quantize_level;
int quantize_method;
int dither_seed;
int compressimg;
char zcmptype[12];
int zbitpix;
int zndim;
long znaxis[6];
long maxtilelen;
long maxelem;
int cn_compressed;
int cn_uncompressed;
int cn_gzip_data;
int cn_zscale;
int cn_zzero;
int cn_zblank;
double zscale;
double zzero;
double cn_bscale;
double cn_bzero;
double cn_actual_bzero;
int zblank;
int rice_blocksize;
int rice_bytepix;
float hcomp_scale;
int hcomp_smooth;
int *tilerow;
long *tiledatasize;
int *tiletype;
void **tiledata;
void **tilenullarray;
int *tileanynull;
char *iobuffer;
long bufrecnum[40];
int dirty[40];
int ageindex[40];
} FITSfile;
typedef struct { int HDUposition;
FITSfile *Fptr;
}fitsfile;
typedef struct { fitsfile *fptr;
int colnum;
char colname[70];
int datatype;
int iotype;
void *array;
long repeat;
long tlmin;
long tlmax;
char tunit[70];
char tdisp[70];
} iteratorCol;
enum { InputCol = 0 };
enum { InputOutputCol = 1 };
enum { OutputCol = 2 };
enum { WCSLIB_GETWCSTAB = 1 };
typedef struct { int i;
int m;
int kind;
char extnam[72];
int extver;
int extlev;
char ttype[72];
long row;
int ndim;
int *dimlen;
double **arrayp;
} wtbarr;
int fits_read_wcstab(fitsfile *fptr, int nwtb, wtbarr *wtb, int *status);
enum { CREATE_DISK_FILE = -106 };
enum { OPEN_DISK_FILE = -105 };
enum { SKIP_TABLE = -104 };
enum { SKIP_IMAGE = -103 };
enum { SKIP_NULL_PRIMARY = -102 };
enum { USE_MEM_BUFF = -101 };
enum { OVERFLOW_ERR = -11 };
enum { PREPEND_PRIMARY = -9 };
enum { SAME_FILE = 101 };
enum { TOO_MANY_FILES = 103 };
enum { FILE_NOT_OPENED = 104 };
enum { FILE_NOT_CREATED = 105 };
enum { WRITE_ERROR = 106 };
enum { END_OF_FILE = 107 };
enum { READ_ERROR = 108 };
enum { FILE_NOT_CLOSED = 110 };
enum { ARRAY_TOO_BIG = 111 };
enum { READONLY_FILE = 112 };
enum { MEMORY_ALLOCATION = 113 };
enum { BAD_FILEPTR = 114 };
enum { NULL_INPUT_PTR = 115 };
enum { SEEK_ERROR = 116 };
enum { BAD_NETTIMEOUT = 117 };
enum { BAD_URL_PREFIX = 121 };
enum { TOO_MANY_DRIVERS = 122 };
enum { DRIVER_INIT_FAILED = 123 };
enum { NO_MATCHING_DRIVER = 124 };
enum { URL_PARSE_ERROR = 125 };
enum { RANGE_PARSE_ERROR = 126 };
enum { SHARED_ERRBASE = 150 };
enum { SHARED_BADARG = 151 };
enum { SHARED_NULPTR = 152 };
enum { SHARED_TABFULL = 153 };
enum { SHARED_NOTINIT = 154 };
enum { SHARED_IPCERR = 155 };
enum { SHARED_NOMEM = 156 };
enum { SHARED_AGAIN = 157 };
enum { SHARED_NOFILE = 158 };
enum { SHARED_NORESIZE = 159 };
enum { HEADER_NOT_EMPTY = 201 };
enum { KEY_NO_EXIST = 202 };
enum { KEY_OUT_BOUNDS = 203 };
enum { VALUE_UNDEFINED = 204 };
enum { NO_QUOTE = 205 };
enum { BAD_INDEX_KEY = 206 };
enum { BAD_KEYCHAR = 207 };
enum { BAD_ORDER = 208 };
enum { NOT_POS_INT = 209 };
enum { NO_END = 210 };
enum { BAD_BITPIX = 211 };
enum { BAD_NAXIS = 212 };
enum { BAD_NAXES = 213 };
enum { BAD_PCOUNT = 214 };
enum { BAD_GCOUNT = 215 };
enum { BAD_TFIELDS = 216 };
enum { NEG_WIDTH = 217 };
enum { NEG_ROWS = 218 };
enum { COL_NOT_FOUND = 219 };
enum { BAD_SIMPLE = 220 };
enum { NO_SIMPLE = 221 };
enum { NO_BITPIX = 222 };
enum { NO_NAXIS = 223 };
enum { NO_NAXES = 224 };
enum { NO_XTENSION = 225 };
enum { NOT_ATABLE = 226 };
enum { NOT_BTABLE = 227 };
enum { NO_PCOUNT = 228 };
enum { NO_GCOUNT = 229 };
enum { NO_TFIELDS = 230 };
enum { NO_TBCOL = 231 };
enum { NO_TFORM = 232 };
enum { NOT_IMAGE = 233 };
enum { BAD_TBCOL = 234 };
enum { NOT_TABLE = 235 };
enum { COL_TOO_WIDE = 236 };
enum { COL_NOT_UNIQUE = 237 };
enum { BAD_ROW_WIDTH = 241 };
enum { UNKNOWN_EXT = 251 };
enum { UNKNOWN_REC = 252 };
enum { END_JUNK = 253 };
enum { BAD_HEADER_FILL = 254 };
enum { BAD_DATA_FILL = 255 };
enum { BAD_TFORM = 261 };
enum { BAD_TFORM_DTYPE = 262 };
enum { BAD_TDIM = 263 };
enum { BAD_HEAP_PTR = 264 };
enum { BAD_HDU_NUM = 301 };
enum { BAD_COL_NUM = 302 };
enum { NEG_FILE_POS = 304 };
enum { NEG_BYTES = 306 };
enum { BAD_ROW_NUM = 307 };
enum { BAD_ELEM_NUM = 308 };
enum { NOT_ASCII_COL = 309 };
enum { NOT_LOGICAL_COL = 310 };
enum { BAD_ATABLE_FORMAT = 311 };
enum { BAD_BTABLE_FORMAT = 312 };
enum { NO_NULL = 314 };
enum { NOT_VARI_LEN = 317 };
enum { BAD_DIMEN = 320 };
enum { BAD_PIX_NUM = 321 };
enum { ZERO_SCALE = 322 };
enum { NEG_AXIS = 323 };
enum { NOT_GROUP_TABLE = 340 };
enum { HDU_ALREADY_MEMBER = 341 };
enum { MEMBER_NOT_FOUND = 342 };
enum { GROUP_NOT_FOUND = 343 };
enum { BAD_GROUP_ID = 344 };
enum { TOO_MANY_HDUS_TRACKED = 345 };
enum { HDU_ALREADY_TRACKED = 346 };
enum { BAD_OPTION = 347 };
enum { IDENTICAL_POINTERS = 348 };
enum { BAD_GROUP_ATTACH = 349 };
enum { BAD_GROUP_DETACH = 350 };
enum { BAD_I2C = 401 };
enum { BAD_F2C = 402 };
enum { BAD_INTKEY = 403 };
enum { BAD_LOGICALKEY = 404 };
enum { BAD_FLOATKEY = 405 };
enum { BAD_DOUBLEKEY = 406 };
enum { BAD_C2I = 407 };
enum { BAD_C2F = 408 };
enum { BAD_C2D = 409 };
enum { BAD_DATATYPE = 410 };
enum { BAD_DECIM = 411 };
enum { NUM_OVERFLOW = 412 };
enum { DATA_COMPRESSION_ERR = 413 };
enum { DATA_DECOMPRESSION_ERR = 414 };
enum { NO_COMPRESSED_TILE = 415 };
enum { BAD_DATE = 420 };
enum { PARSE_SYNTAX_ERR = 431 };
enum { PARSE_BAD_TYPE = 432 };
enum { PARSE_LRG_VECTOR = 433 };
enum { PARSE_NO_OUTPUT = 434 };
enum { PARSE_BAD_COL = 435 };
enum { PARSE_BAD_OUTPUT = 436 };
enum { ANGLE_TOO_BIG = 501 };
enum { BAD_WCS_VAL = 502 };
enum { WCS_ERROR = 503 };
enum { BAD_WCS_PROJ = 504 };
enum { NO_WCS_KEY = 505 };
enum { APPROX_WCS_KEY = 506 };
enum { NO_CLOSE_ERROR = 999 };
enum { NGP_ERRBASE = 360 };
enum { NGP_OK = 0 };
enum { NGP_NO_MEMORY = 360 };
enum { NGP_READ_ERR = 361 };
enum { NGP_NUL_PTR = 362 };
enum { NGP_EMPTY_CURLINE = 363 };
enum { NGP_UNREAD_QUEUE_FULL = 364 };
enum { NGP_INC_NESTING = 365 };
enum { NGP_ERR_FOPEN = 366 };
enum { NGP_EOF = 367 };
enum { NGP_BAD_ARG = 368 };
enum { NGP_TOKEN_NOT_EXPECT = 369 };
int CFITS2Unit( fitsfile *fptr );
fitsfile* CUnit2FITS(int unit);
int fits_get_token (char **ptr, char *delimiter, char *token, int *isanumber);
int fits_get_token2(char **ptr, char *delimiter, char **token, int *isanumber, int *status);
char *fits_split_names(char *list);
int ffiurl( char *url, char *urltype, char *infile, char *outfile, char *extspec, char *rowfilter, char *binspec, char *colspec, int *status);
int ffifile (char *url, char *urltype, char *infile, char *outfile, char *extspec, char *rowfilter, char *binspec, char *colspec, char *pixfilter, int *status);
int ffifile2 (char *url, char *urltype, char *infile, char *outfile, char *extspec, char *rowfilter, char *binspec, char *colspec, char *pixfilter, char *compspec, int *status);
int ffrtnm(char *url, char *rootname, int *status);
int ffexist(const char *infile, int *exists, int *status);
int ffexts(char *extspec, int *extnum, char *extname, int *extvers, int *hdutype, char *colname, char *rowexpress, int *status);
int ffextn(char *url, int *extension_num, int *status);
int ffurlt(fitsfile *fptr, char *urlType, int *status);
int ffbins(char *binspec, int *imagetype, int *haxis, char colname[4][71], double *minin, double *maxin, double *binsizein, char minname[4][71], char maxname[4][71], char binname[4][71], double *weight, char *wtname, int *recip, int *status);
int ffbinr(char **binspec, char *colname, double *minin, double *maxin, double *binsizein, char *minname, char *maxname, char *binname, int *status);
int fits_copy_cell2image(fitsfile *fptr, fitsfile *newptr, char *colname, long rownum, int *status);
int fits_copy_image2cell(fitsfile *fptr, fitsfile *newptr, char *colname, long rownum, int copykeyflag, int *status);
int fits_copy_pixlist2image(fitsfile *infptr, fitsfile *outfptr, int firstkey, int naxis, int *colnum, int *status);
int ffimport_file( char *filename, char **contents, int *status );
int ffrwrg( char *rowlist, LONGLONG maxrows, int maxranges, int *numranges, long *minrow, long *maxrow, int *status);
int ffrwrgll( char *rowlist, LONGLONG maxrows, int maxranges, int *numranges, LONGLONG *minrow, LONGLONG *maxrow, int *status);
int fits_init_cfitsio(void);
int ffomem(fitsfile **fptr, const char *name, int mode, void **buffptr, size_t *buffsize, size_t deltasize, void *(*mem_realloc)(void *p, size_t newsize), int *status);
int ffopen(fitsfile **fptr, const char *filename, int iomode, int *status);
int ffopentest(int soname, fitsfile **fptr, const char *filename, int iomode, int *status);
int ffdopn(fitsfile **fptr, const char *filename, int iomode, int *status);
int ffeopn(fitsfile **fptr, const char *filename, int iomode, char *extlist, int *hdutype, int *status);
int fftopn(fitsfile **fptr, const char *filename, int iomode, int *status);
int ffiopn(fitsfile **fptr, const char *filename, int iomode, int *status);
int ffdkopn(fitsfile **fptr, const char *filename, int iomode, int *status);
int ffreopen(fitsfile *openfptr, fitsfile **newfptr, int *status);
int ffinit( fitsfile **fptr, const char *filename, int *status);
int ffdkinit(fitsfile **fptr, const char *filename, int *status);
int ffimem(fitsfile **fptr, void **buffptr, size_t *buffsize, size_t deltasize, void *(*mem_realloc)(void *p, size_t newsize), int *status);
int fftplt(fitsfile **fptr, const char *filename, const char *tempname, int *status);
int ffflus(fitsfile *fptr, int *status);
int ffflsh(fitsfile *fptr, int clearbuf, int *status);
int ffclos(fitsfile *fptr, int *status);
int ffdelt(fitsfile *fptr, int *status);
int ffflnm(fitsfile *fptr, char *filename, int *status);
int ffflmd(fitsfile *fptr, int *filemode, int *status);
int fits_delete_iraf_file(const char *filename, int *status);
float ffvers(float *version);
void ffupch(char *string);
void ffgerr(int status, char *errtext);
void ffpmsg(const char *err_message);
void ffpmrk(void);
int ffgmsg(char *err_message);
void ffcmsg(void);
void ffcmrk(void);
void ffrprt(FILE *stream, int status);
void ffcmps(char *templt, char *colname, int casesen, int *match, int *exact);
int fftkey(const char *keyword, int *status);
int fftrec(char *card, int *status);
int ffnchk(fitsfile *fptr, int *status);
int ffkeyn(const char *keyroot, int value, char *keyname, int *status);
int ffnkey(int value, const char *keyroot, char *keyname, int *status);
int ffgkcl(char *card);
int ffdtyp(const char *cval, char *dtype, int *status);
int ffinttyp(char *cval, int *datatype, int *negative, int *status);
int ffpsvc(char *card, char *value, char *comm, int *status);
int ffgknm(char *card, char *name, int *length, int *status);
int ffgthd(char *tmplt, char *card, int *hdtype, int *status);
int ffmkky(const char *keyname, char *keyval, const char *comm, char *card, int *status);
int fits_translate_keyword(char *inrec, char *outrec, char *patterns[][2], int npat, int n_value, int n_offset, int n_range, int *pat_num, int *i, int *j, int *m, int *n, int *status);
int fits_translate_keywords(fitsfile *infptr, fitsfile *outfptr, int firstkey, char *patterns[][2], int npat, int n_value, int n_offset, int n_range, int *status);
int ffasfm(char *tform, int *datacode, long *width, int *decim, int *status);
int ffbnfm(char *tform, int *datacode, long *repeat, long *width, int *status);
int ffbnfmll(char *tform, int *datacode, LONGLONG *repeat, long *width, int *status);
int ffgabc(int tfields, char **tform, int space, long *rowlen, long *tbcol, int *status);
int fits_get_section_range(char **ptr,long *secmin,long *secmax,long *incre, int *status);
int ffmbyt(fitsfile *fptr, LONGLONG bytpos, int ignore_err, int *status);
int ffpky(fitsfile *fptr, int datatype, const char *keyname, void *value, const char *comm, int *status);
int ffprec(fitsfile *fptr, const char *card, int *status);
int ffpcom(fitsfile *fptr, const char *comm, int *status);
int ffpunt(fitsfile *fptr, const char *keyname, const char *unit, int *status);
int ffphis(fitsfile *fptr, const char *history, int *status);
int ffpdat(fitsfile *fptr, int *status);
int ffverifydate(int year, int month, int day, int *status);
int ffgstm(char *timestr, int *timeref, int *status);
int ffgsdt(int *day, int *month, int *year, int *status);
int ffdt2s(int year, int month, int day, char *datestr, int *status);
int fftm2s(int year, int month, int day, int hour, int minute, double second, int decimals, char *datestr, int *status);
int ffs2dt(char *datestr, int *year, int *month, int *day, int *status);
int ffs2tm(char *datestr, int *year, int *month, int *day, int *hour, int *minute, double *second, int *status);
int ffpkyu(fitsfile *fptr, const char *keyname, const char *comm, int *status);
int ffpkys(fitsfile *fptr, const char *keyname, const char *value, const char *comm,int *status);
int ffpkls(fitsfile *fptr, const char *keyname, const char *value, const char *comm,int *status);
int ffplsw(fitsfile *fptr, int *status);
int ffpkyl(fitsfile *fptr, const char *keyname, int value, const char *comm, int *status);
int ffpkyj(fitsfile *fptr, const char *keyname, LONGLONG value, const char *comm, int *status);
int ffpkyuj(fitsfile *fptr, const char *keyname, ULONGLONG value, const char *comm, int *status);
int ffpkyf(fitsfile *fptr, const char *keyname, float value, int decim, const char *comm, int *status);
int ffpkye(fitsfile *fptr, const char *keyname, float value, int decim, const char *comm, int *status);
int ffpkyg(fitsfile *fptr, const char *keyname, double value, int decim, const char *comm, int *status);
int ffpkyd(fitsfile *fptr, const char *keyname, double value, int decim, const char *comm, int *status);
int ffpkyc(fitsfile *fptr, const char *keyname, float *value, int decim, const char *comm, int *status);
int ffpkym(fitsfile *fptr, const char *keyname, double *value, int decim, const char *comm, int *status);
int ffpkfc(fitsfile *fptr, const char *keyname, float *value, int decim, const char *comm, int *status);
int ffpkfm(fitsfile *fptr, const char *keyname, double *value, int decim, const char *comm, int *status);
int ffpkyt(fitsfile *fptr, const char *keyname, long intval, double frac, const char *comm, int *status);
int ffptdm( fitsfile *fptr, int colnum, int naxis, long naxes[], int *status);
int ffptdmll( fitsfile *fptr, int colnum, int naxis, LONGLONG naxes[], int *status);
int ffpkns(fitsfile *fptr, const char *keyroot, int nstart, int nkey, char *value[], char *comm[], int *status);
int ffpknl(fitsfile *fptr, const char *keyroot, int nstart, int nkey, int *value, char *comm[], int *status);
int ffpknj(fitsfile *fptr, const char *keyroot, int nstart, int nkey, long *value, char *comm[], int *status);
int ffpknjj(fitsfile *fptr, const char *keyroot, int nstart, int nkey, LONGLONG *value, char *comm[], int *status);
int ffpknf(fitsfile *fptr, const char *keyroot, int nstart, int nkey, float *value, int decim, char *comm[], int *status);
int ffpkne(fitsfile *fptr, const char *keyroot, int nstart, int nkey, float *value, int decim, char *comm[], int *status);
int ffpkng(fitsfile *fptr, const char *keyroot, int nstart, int nkey, double *value, int decim, char *comm[], int *status);
int ffpknd(fitsfile *fptr, const char *keyroot, int nstart, int nkey, double *value, int decim, char *comm[], int *status);
int ffcpky(fitsfile *infptr,fitsfile *outfptr,int incol,int outcol, char *rootname, int *status);
int ffphps( fitsfile *fptr, int bitpix, int naxis, long naxes[], int *status);
int ffphpsll( fitsfile *fptr, int bitpix, int naxis, LONGLONG naxes[], int *status);
int ffphpr( fitsfile *fptr, int simple, int bitpix, int naxis, long naxes[], LONGLONG pcount, LONGLONG gcount, int extend, int *status);
int ffphprll( fitsfile *fptr, int simple, int bitpix, int naxis, LONGLONG naxes[], LONGLONG pcount, LONGLONG gcount, int extend, int *status);
int ffphtb(fitsfile *fptr, LONGLONG naxis1, LONGLONG naxis2, int tfields, char **ttype, long *tbcol, char **tform, char **tunit, const char *extname, int *status);
int ffphbn(fitsfile *fptr, LONGLONG naxis2, int tfields, char **ttype, char **tform, char **tunit, const char *extname, LONGLONG pcount, int *status);
int ffphext( fitsfile *fptr, const char *xtension, int bitpix, int naxis, long naxes[], LONGLONG pcount, LONGLONG gcount, int *status);
int ffpktp(fitsfile *fptr, const char *filename, int *status);
int ffghsp(fitsfile *fptr, int *nexist, int *nmore, int *status);
int ffghps(fitsfile *fptr, int *nexist, int *position, int *status);
int ffmaky(fitsfile *fptr, int nrec, int *status);
int ffmrky(fitsfile *fptr, int nrec, int *status);
int ffgnxk(fitsfile *fptr, char **inclist, int ninc, char **exclist, int nexc, char *card, int *status);
int ffgrec(fitsfile *fptr, int nrec, char *card, int *status);
int ffgcrd(fitsfile *fptr, const char *keyname, char *card, int *status);
int ffgstr(fitsfile *fptr, const char *string, char *card, int *status);
int ffgunt(fitsfile *fptr, const char *keyname, char *unit, int *status);
int ffgkyn(fitsfile *fptr, int nkey, char *keyname, char *keyval, char *comm, int *status);
int ffgkey(fitsfile *fptr, const char *keyname, char *keyval, char *comm, int *status);
int ffgky( fitsfile *fptr, int datatype, const char *keyname, void *value, char *comm, int *status);
int ffgkys(fitsfile *fptr, const char *keyname, char *value, char *comm, int *status);
int ffgksl(fitsfile *fptr, const char *keyname, int *length, int *status);
int ffgkls(fitsfile *fptr, const char *keyname, char **value, char *comm, int *status);
int ffgsky(fitsfile *fptr, const char *keyname, int firstchar, int maxchar, char *value, int *valuelen, char *comm, int *status);
int fffree(void *value, int *status);
int fffkls(char *value, int *status);
int ffgkyl(fitsfile *fptr, const char *keyname, int *value, char *comm, int *status);
int ffgkyj(fitsfile *fptr, const char *keyname, long *value, char *comm, int *status);
int ffgkyjj(fitsfile *fptr, const char *keyname, LONGLONG *value, char *comm, int *status);
int ffgkyujj(fitsfile *fptr, const char *keyname, ULONGLONG *value, char *comm, int *status);
int ffgkye(fitsfile *fptr, const char *keyname, float *value, char *comm,int *status);
int ffgkyd(fitsfile *fptr, const char *keyname, double *value,char *comm,int *status);
int ffgkyc(fitsfile *fptr, const char *keyname, float *value, char *comm,int *status);
int ffgkym(fitsfile *fptr, const char *keyname, double *value,char *comm,int *status);
int ffgkyt(fitsfile *fptr, const char *keyname, long *ivalue, double *dvalue, char *comm, int *status);
int ffgtdm(fitsfile *fptr, int colnum, int maxdim, int *naxis, long naxes[], int *status);
int ffgtdmll(fitsfile *fptr, int colnum, int maxdim, int *naxis, LONGLONG naxes[], int *status);
int ffdtdm(fitsfile *fptr, char *tdimstr, int colnum, int maxdim, int *naxis, long naxes[], int *status);
int ffdtdmll(fitsfile *fptr, char *tdimstr, int colnum, int maxdim, int *naxis, LONGLONG naxes[], int *status);
int ffgkns(fitsfile *fptr, const char *keyname, int nstart, int nmax, char *value[], int *nfound, int *status);
int ffgknl(fitsfile *fptr, const char *keyname, int nstart, int nmax, int *value, int *nfound, int *status);
int ffgknj(fitsfile *fptr, const char *keyname, int nstart, int nmax, long *value, int *nfound, int *status);
int ffgknjj(fitsfile *fptr, const char *keyname, int nstart, int nmax, LONGLONG *value, int *nfound, int *status);
int ffgkne(fitsfile *fptr, const char *keyname, int nstart, int nmax, float *value, int *nfound, int *status);
int ffgknd(fitsfile *fptr, const char *keyname, int nstart, int nmax, double *value, int *nfound, int *status);
int ffh2st(fitsfile *fptr, char **header, int *status);
int ffhdr2str( fitsfile *fptr, int exclude_comm, char **exclist, int nexc, char **header, int *nkeys, int *status);
int ffcnvthdr2str( fitsfile *fptr, int exclude_comm, char **exclist, int nexc, char **header, int *nkeys, int *status);
int ffghpr(fitsfile *fptr, int maxdim, int *simple, int *bitpix, int *naxis, long naxes[], long *pcount, long *gcount, int *extend, int *status);
int ffghprll(fitsfile *fptr, int maxdim, int *simple, int *bitpix, int *naxis, LONGLONG naxes[], long *pcount, long *gcount, int *extend, int *status);
int ffghtb(fitsfile *fptr,int maxfield, long *naxis1, long *naxis2, int *tfields, char **ttype, long *tbcol, char **tform, char **tunit, char *extname, int *status);
int ffghtbll(fitsfile *fptr,int maxfield, LONGLONG *naxis1, LONGLONG *naxis2, int *tfields, char **ttype, LONGLONG *tbcol, char **tform, char **tunit, char *extname, int *status);
int ffghbn(fitsfile *fptr, int maxfield, long *naxis2, int *tfields, char **ttype, char **tform, char **tunit, char *extname, long *pcount, int *status);
int ffghbnll(fitsfile *fptr, int maxfield, LONGLONG *naxis2, int *tfields, char **ttype, char **tform, char **tunit, char *extname, LONGLONG *pcount, int *status);
int ffuky(fitsfile *fptr, int datatype, const char *keyname, void *value, const char *comm, int *status);
int ffucrd(fitsfile *fptr, const char *keyname, const char *card, int *status);
int ffukyu(fitsfile *fptr, const char *keyname, const char *comm, int *status);
int ffukys(fitsfile *fptr, const char *keyname, const char *value, const char *comm, int *status);
int ffukls(fitsfile *fptr, const char *keyname, const char *value, const char *comm, int *status);
int ffukyl(fitsfile *fptr, const char *keyname, int value, const char *comm, int *status);
int ffukyj(fitsfile *fptr, const char *keyname, LONGLONG value, const char *comm, int *status);
int ffukyf(fitsfile *fptr, const char *keyname, float value, int decim, const char *comm, int *status);
int ffukye(fitsfile *fptr, const char *keyname, float value, int decim, const char *comm, int *status);
int ffukyg(fitsfile *fptr, const char *keyname, double value, int decim, const char *comm, int *status);
int ffukyd(fitsfile *fptr, const char *keyname, double value, int decim, const char *comm, int *status);
int ffukyc(fitsfile *fptr, const char *keyname, float *value, int decim, const char *comm, int *status);
int ffukym(fitsfile *fptr, const char *keyname, double *value, int decim, const char *comm, int *status);
int ffukfc(fitsfile *fptr, const char *keyname, float *value, int decim, const char *comm, int *status);
int ffukfm(fitsfile *fptr, const char *keyname, double *value, int decim, const char *comm, int *status);
int ffmrec(fitsfile *fptr, int nkey, const char *card, int *status);
int ffmcrd(fitsfile *fptr, const char *keyname, const char *card, int *status);
int ffmnam(fitsfile *fptr, const char *oldname, const char *newname, int *status);
int ffmcom(fitsfile *fptr, const char *keyname, const char *comm, int *status);
int ffmkyu(fitsfile *fptr, const char *keyname, const char *comm, int *status);
int ffmkys(fitsfile *fptr, const char *keyname, const char *value, const char *comm,int *status);
int ffmkls(fitsfile *fptr, const char *keyname, const char *value, const char *comm,int *status);
int ffmkyl(fitsfile *fptr, const char *keyname, int value, const char *comm, int *status);
int ffmkyj(fitsfile *fptr, const char *keyname, LONGLONG value, const char *comm, int *status);
int ffmkyf(fitsfile *fptr, const char *keyname, float value, int decim, const char *comm, int *status);
int ffmkye(fitsfile *fptr, const char *keyname, float value, int decim, const char *comm, int *status);
int ffmkyg(fitsfile *fptr, const char *keyname, double value, int decim, const char *comm, int *status);
int ffmkyd(fitsfile *fptr, const char *keyname, double value, int decim, const char *comm, int *status);
int ffmkyc(fitsfile *fptr, const char *keyname, float *value, int decim, const char *comm, int *status);
int ffmkym(fitsfile *fptr, const char *keyname, double *value, int decim, const char *comm, int *status);
int ffmkfc(fitsfile *fptr, const char *keyname, float *value, int decim, const char *comm, int *status);
int ffmkfm(fitsfile *fptr, const char *keyname, double *value, int decim, const char *comm, int *status);
int ffirec(fitsfile *fptr, int nkey, const char *card, int *status);
int ffikey(fitsfile *fptr, const char *card, int *status);
int ffikyu(fitsfile *fptr, const char *keyname, const char *comm, int *status);
int ffikys(fitsfile *fptr, const char *keyname, const char *value, const char *comm,int *status);
int ffikls(fitsfile *fptr, const char *keyname, const char *value, const char *comm,int *status);
int ffikyl(fitsfile *fptr, const char *keyname, int value, const char *comm, int *status);
int ffikyj(fitsfile *fptr, const char *keyname, LONGLONG value, const char *comm, int *status);
int ffikyf(fitsfile *fptr, const char *keyname, float value, int decim, const char *comm, int *status);
int ffikye(fitsfile *fptr, const char *keyname, float value, int decim, const char *comm, int *status);
int ffikyg(fitsfile *fptr, const char *keyname, double value, int decim, const char *comm, int *status);
int ffikyd(fitsfile *fptr, const char *keyname, double value, int decim, const char *comm, int *status);
int ffikyc(fitsfile *fptr, const char *keyname, float *value, int decim, const char *comm, int *status);
int ffikym(fitsfile *fptr, const char *keyname, double *value, int decim, const char *comm, int *status);
int ffikfc(fitsfile *fptr, const char *keyname, float *value, int decim, const char *comm, int *status);
int ffikfm(fitsfile *fptr, const char *keyname, double *value, int decim, const char *comm, int *status);
int ffdkey(fitsfile *fptr, const char *keyname, int *status);
int ffdstr(fitsfile *fptr, const char *string, int *status);
int ffdrec(fitsfile *fptr, int keypos, int *status);
int ffghdn(fitsfile *fptr, int *chdunum);
int ffghdt(fitsfile *fptr, int *exttype, int *status);
int ffghad(fitsfile *fptr, long *headstart, long *datastart, long *dataend, int *status);
int ffghadll(fitsfile *fptr, LONGLONG *headstart, LONGLONG *datastart, LONGLONG *dataend, int *status);
int ffghof(fitsfile *fptr, off_t *headstart, off_t *datastart, off_t *dataend, int *status);
int ffgipr(fitsfile *fptr, int maxaxis, int *imgtype, int *naxis, long *naxes, int *status);
int ffgiprll(fitsfile *fptr, int maxaxis, int *imgtype, int *naxis, LONGLONG *naxes, int *status);
int ffgidt(fitsfile *fptr, int *imgtype, int *status);
int ffgiet(fitsfile *fptr, int *imgtype, int *status);
int ffgidm(fitsfile *fptr, int *naxis, int *status);
int ffgisz(fitsfile *fptr, int nlen, long *naxes, int *status);
int ffgiszll(fitsfile *fptr, int nlen, LONGLONG *naxes, int *status);
int ffmahd(fitsfile *fptr, int hdunum, int *exttype, int *status);
int ffmrhd(fitsfile *fptr, int hdumov, int *exttype, int *status);
int ffmnhd(fitsfile *fptr, int exttype, char *hduname, int hduvers, int *status);
int ffthdu(fitsfile *fptr, int *nhdu, int *status);
int ffcrhd(fitsfile *fptr, int *status);
int ffcrim(fitsfile *fptr, int bitpix, int naxis, long *naxes, int *status);
int ffcrimll(fitsfile *fptr, int bitpix, int naxis, LONGLONG *naxes, int *status);
int ffcrtb(fitsfile *fptr, int tbltype, LONGLONG naxis2, int tfields, char **ttype, char **tform, char **tunit, const char *extname, int *status);
int ffiimg(fitsfile *fptr, int bitpix, int naxis, long *naxes, int *status);
int ffiimgll(fitsfile *fptr, int bitpix, int naxis, LONGLONG *naxes, int *status);
int ffitab(fitsfile *fptr, LONGLONG naxis1, LONGLONG naxis2, int tfields, char **ttype, long *tbcol, char **tform, char **tunit, const char *extname, int *status);
int ffibin(fitsfile *fptr, LONGLONG naxis2, int tfields, char **ttype, char **tform, char **tunit, const char *extname, LONGLONG pcount, int *status);
int ffrsim(fitsfile *fptr, int bitpix, int naxis, long *naxes, int *status);
int ffrsimll(fitsfile *fptr, int bitpix, int naxis, LONGLONG *naxes, int *status);
int ffdhdu(fitsfile *fptr, int *hdutype, int *status);
int ffcopy(fitsfile *infptr, fitsfile *outfptr, int morekeys, int *status);
int ffcpfl(fitsfile *infptr, fitsfile *outfptr, int prev, int cur, int follow, int *status);
int ffcphd(fitsfile *infptr, fitsfile *outfptr, int *status);
int ffcpdt(fitsfile *infptr, fitsfile *outfptr, int *status);
int ffchfl(fitsfile *fptr, int *status);
int ffcdfl(fitsfile *fptr, int *status);
int ffwrhdu(fitsfile *fptr, FILE *outstream, int *status);
int ffrdef(fitsfile *fptr, int *status);
int ffrhdu(fitsfile *fptr, int *hdutype, int *status);
int ffhdef(fitsfile *fptr, int morekeys, int *status);
int ffpthp(fitsfile *fptr, long theap, int *status);
int ffcsum(fitsfile *fptr, long nrec, unsigned long *sum, int *status);
void ffesum(unsigned long sum, int complm, char *ascii);
unsigned long ffdsum(char *ascii, int complm, unsigned long *sum);
int ffpcks(fitsfile *fptr, int *status);
int ffupck(fitsfile *fptr, int *status);
int ffvcks(fitsfile *fptr, int *datastatus, int *hdustatus, int *status);
int ffgcks(fitsfile *fptr, unsigned long *datasum, unsigned long *hdusum, int *status);
int ffpscl(fitsfile *fptr, double scale, double zeroval, int *status);
int ffpnul(fitsfile *fptr, LONGLONG nulvalue, int *status);
int fftscl(fitsfile *fptr, int colnum, double scale, double zeroval, int *status);
int fftnul(fitsfile *fptr, int colnum, LONGLONG nulvalue, int *status);
int ffsnul(fitsfile *fptr, int colnum, char *nulstring, int *status);
int ffgcno(fitsfile *fptr, int casesen, char *templt, int *colnum, int *status);
int ffgcnn(fitsfile *fptr, int casesen, char *templt, char *colname, int *colnum, int *status);
int ffgtcl(fitsfile *fptr, int colnum, int *typecode, long *repeat, long *width, int *status);
int ffgtclll(fitsfile *fptr, int colnum, int *typecode, LONGLONG *repeat, LONGLONG *width, int *status);
int ffeqty(fitsfile *fptr, int colnum, int *typecode, long *repeat, long *width, int *status);
int ffeqtyll(fitsfile *fptr, int colnum, int *typecode, LONGLONG *repeat, LONGLONG *width, int *status);
int ffgncl(fitsfile *fptr, int *ncols, int *status);
int ffgnrw(fitsfile *fptr, long *nrows, int *status);
int ffgnrwll(fitsfile *fptr, LONGLONG *nrows, int *status);
int ffgacl(fitsfile *fptr, int colnum, char *ttype, long *tbcol, char *tunit, char *tform, double *tscal, double *tzero, char *tnull, char *tdisp, int *status);
int ffgbcl(fitsfile *fptr, int colnum, char *ttype, char *tunit, char *dtype, long *repeat, double *tscal, double *tzero, long *tnull, char *tdisp, int *status);
int ffgbclll(fitsfile *fptr, int colnum, char *ttype, char *tunit, char *dtype, LONGLONG *repeat, double *tscal, double *tzero, LONGLONG *tnull, char *tdisp, int *status);
int ffgrsz(fitsfile *fptr, long *nrows, int *status);
int ffgcdw(fitsfile *fptr, int colnum, int *width, int *status);
int ffgpxv(fitsfile *fptr, int datatype, long *firstpix, LONGLONG nelem, void *nulval, void *array, int *anynul, int *status);
int ffgpxvll(fitsfile *fptr, int datatype, LONGLONG *firstpix, LONGLONG nelem, void *nulval, void *array, int *anynul, int *status);
int ffgpxf(fitsfile *fptr, int datatype, long *firstpix, LONGLONG nelem, void *array, char *nullarray, int *anynul, int *status);
int ffgpxfll(fitsfile *fptr, int datatype, LONGLONG *firstpix, LONGLONG nelem, void *array, char *nullarray, int *anynul, int *status);
int ffgsv(fitsfile *fptr, int datatype, long *blc, long *trc, long *inc, void *nulval, void *array, int *anynul, int *status);
int ffgpv(fitsfile *fptr, int datatype, LONGLONG firstelem, LONGLONG nelem, void *nulval, void *array, int *anynul, int *status);
int ffgpf(fitsfile *fptr, int datatype, LONGLONG firstelem, LONGLONG nelem, void *array, char *nullarray, int *anynul, int *status);
int ffgpvb(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, unsigned char nulval, unsigned char *array, int *anynul, int *status);
int ffgpvsb(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, signed char nulval, signed char *array, int *anynul, int *status);
int ffgpvui(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, unsigned short nulval, unsigned short *array, int *anynul, int *status);
int ffgpvi(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, short nulval, short *array, int *anynul, int *status);
int ffgpvuj(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, unsigned long nulval, unsigned long *array, int *anynul, int *status);
int ffgpvj(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, long nulval, long *array, int *anynul, int *status);
int ffgpvujj(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, ULONGLONG nulval, ULONGLONG *array, int *anynul, int *status);
int ffgpvjj(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, LONGLONG nulval, LONGLONG *array, int *anynul, int *status);
int ffgpvuk(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, unsigned int nulval, unsigned int *array, int *anynul, int *status);
int ffgpvk(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, int nulval, int *array, int *anynul, int *status);
int ffgpve(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, float nulval, float *array, int *anynul, int *status);
int ffgpvd(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, double nulval, double *array, int *anynul, int *status);
int ffgpfb(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, unsigned char *array, char *nularray, int *anynul, int *status);
int ffgpfsb(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, signed char *array, char *nularray, int *anynul, int *status);
int ffgpfui(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, unsigned short *array, char *nularray, int *anynul, int *status);
int ffgpfi(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, short *array, char *nularray, int *anynul, int *status);
int ffgpfuj(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, unsigned long *array, char *nularray, int *anynul, int *status);
int ffgpfj(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, long *array, char *nularray, int *anynul, int *status);
int ffgpfujj(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, ULONGLONG *array, char *nularray, int *anynul, int *status);
int ffgpfjj(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, LONGLONG *array, char *nularray, int *anynul, int *status);
int ffgpfuk(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, unsigned int *array, char *nularray, int *anynul, int *status);
int ffgpfk(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, int *array, char *nularray, int *anynul, int *status);
int ffgpfe(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, float *array, char *nularray, int *anynul, int *status);
int ffgpfd(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, double *array, char *nularray, int *anynul, int *status);
int ffg2db(fitsfile *fptr, long group, unsigned char nulval, LONGLONG ncols, LONGLONG naxis1, LONGLONG naxis2, unsigned char *array, int *anynul, int *status);
int ffg2dsb(fitsfile *fptr, long group, signed char nulval, LONGLONG ncols, LONGLONG naxis1, LONGLONG naxis2, signed char *array, int *anynul, int *status);
int ffg2dui(fitsfile *fptr, long group, unsigned short nulval, LONGLONG ncols, LONGLONG naxis1, LONGLONG naxis2, unsigned short *array, int *anynul, int *status);
int ffg2di(fitsfile *fptr, long group, short nulval, LONGLONG ncols, LONGLONG naxis1, LONGLONG naxis2, short *array, int *anynul, int *status);
int ffg2duj(fitsfile *fptr, long group, unsigned long nulval, LONGLONG ncols, LONGLONG naxis1, LONGLONG naxis2, unsigned long *array, int *anynul, int *status);
int ffg2dj(fitsfile *fptr, long group, long nulval, LONGLONG ncols, LONGLONG naxis1, LONGLONG naxis2, long *array, int *anynul, int *status);
int ffg2dujj(fitsfile *fptr, long group, ULONGLONG nulval, LONGLONG ncols, LONGLONG naxis1, LONGLONG naxis2, ULONGLONG *array, int *anynul, int *status);
int ffg2djj(fitsfile *fptr, long group, LONGLONG nulval, LONGLONG ncols, LONGLONG naxis1, LONGLONG naxis2, LONGLONG *array, int *anynul, int *status);
int ffg2duk(fitsfile *fptr, long group, unsigned int nulval, LONGLONG ncols, LONGLONG naxis1, LONGLONG naxis2, unsigned int *array, int *anynul, int *status);
int ffg2dk(fitsfile *fptr, long group, int nulval, LONGLONG ncols, LONGLONG naxis1, LONGLONG naxis2, int *array, int *anynul, int *status);
int ffg2de(fitsfile *fptr, long group, float nulval, LONGLONG ncols, LONGLONG naxis1, LONGLONG naxis2, float *array, int *anynul, int *status);
int ffg2dd(fitsfile *fptr, long group, double nulval, LONGLONG ncols, LONGLONG naxis1, LONGLONG naxis2, double *array, int *anynul, int *status);
int ffg3db(fitsfile *fptr, long group, unsigned char nulval, LONGLONG ncols, LONGLONG nrows, LONGLONG naxis1, LONGLONG naxis2, LONGLONG naxis3, unsigned char *array, int *anynul, int *status);
int ffg3dsb(fitsfile *fptr, long group, signed char nulval, LONGLONG ncols, LONGLONG nrows, LONGLONG naxis1, LONGLONG naxis2, LONGLONG naxis3, signed char *array, int *anynul, int *status);
int ffg3dui(fitsfile *fptr, long group, unsigned short nulval, LONGLONG ncols, LONGLONG nrows, LONGLONG naxis1, LONGLONG naxis2, LONGLONG naxis3, unsigned short *array, int *anynul, int *status);
int ffg3di(fitsfile *fptr, long group, short nulval, LONGLONG ncols, LONGLONG nrows, LONGLONG naxis1, LONGLONG naxis2, LONGLONG naxis3, short *array, int *anynul, int *status);
int ffg3duj(fitsfile *fptr, long group, unsigned long nulval, LONGLONG ncols, LONGLONG nrows, LONGLONG naxis1, LONGLONG naxis2, LONGLONG naxis3, unsigned long *array, int *anynul, int *status);
int ffg3dj(fitsfile *fptr, long group, long nulval, LONGLONG ncols, LONGLONG nrows, LONGLONG naxis1, LONGLONG naxis2, LONGLONG naxis3, long *array, int *anynul, int *status);
int ffg3dujj(fitsfile *fptr, long group, ULONGLONG nulval, LONGLONG ncols, LONGLONG nrows, LONGLONG naxis1, LONGLONG naxis2, LONGLONG naxis3, ULONGLONG *array, int *anynul, int *status);
int ffg3djj(fitsfile *fptr, long group, LONGLONG nulval, LONGLONG ncols, LONGLONG nrows, LONGLONG naxis1, LONGLONG naxis2, LONGLONG naxis3, LONGLONG *array, int *anynul, int *status);
int ffg3duk(fitsfile *fptr, long group, unsigned int nulval, LONGLONG ncols, LONGLONG nrows, LONGLONG naxis1, LONGLONG naxis2, LONGLONG naxis3, unsigned int *array, int *anynul, int *status);
int ffg3dk(fitsfile *fptr, long group, int nulval, LONGLONG ncols, LONGLONG nrows, LONGLONG naxis1, LONGLONG naxis2, LONGLONG naxis3, int *array, int *anynul, int *status);
int ffg3de(fitsfile *fptr, long group, float nulval, LONGLONG ncols, LONGLONG nrows, LONGLONG naxis1, LONGLONG naxis2, LONGLONG naxis3, float *array, int *anynul, int *status);
int ffg3dd(fitsfile *fptr, long group, double nulval, LONGLONG ncols, LONGLONG nrows, LONGLONG naxis1, LONGLONG naxis2, LONGLONG naxis3, double *array, int *anynul, int *status);
int ffgsvb(fitsfile *fptr, int colnum, int naxis, long *naxes, long *blc, long *trc, long *inc, unsigned char nulval, unsigned char *array, int *anynul, int *status);
int ffgsvsb(fitsfile *fptr, int colnum, int naxis, long *naxes, long *blc, long *trc, long *inc, signed char nulval, signed char *array, int *anynul, int *status);
int ffgsvui(fitsfile *fptr, int colnum, int naxis, long *naxes, long *blc, long *trc, long *inc, unsigned short nulval, unsigned short *array, int *anynul, int *status);
int ffgsvi(fitsfile *fptr, int colnum, int naxis, long *naxes, long *blc, long *trc, long *inc, short nulval, short *array, int *anynul, int *status);
int ffgsvuj(fitsfile *fptr, int colnum, int naxis, long *naxes, long *blc, long *trc, long *inc, unsigned long nulval, unsigned long *array, int *anynul, int *status);
int ffgsvj(fitsfile *fptr, int colnum, int naxis, long *naxes, long *blc, long *trc, long *inc, long nulval, long *array, int *anynul, int *status);
int ffgsvujj(fitsfile *fptr, int colnum, int naxis, long *naxes, long *blc, long *trc, long *inc, ULONGLONG nulval, ULONGLONG *array, int *anynul, int *status);
int ffgsvjj(fitsfile *fptr, int colnum, int naxis, long *naxes, long *blc, long *trc, long *inc, LONGLONG nulval, LONGLONG *array, int *anynul, int *status);
int ffgsvuk(fitsfile *fptr, int colnum, int naxis, long *naxes, long *blc, long *trc, long *inc, unsigned int nulval, unsigned int *array, int *anynul, int *status);
int ffgsvk(fitsfile *fptr, int colnum, int naxis, long *naxes, long *blc, long *trc, long *inc, int nulval, int *array, int *anynul, int *status);
int ffgsve(fitsfile *fptr, int colnum, int naxis, long *naxes, long *blc, long *trc, long *inc, float nulval, float *array, int *anynul, int *status);
int ffgsvd(fitsfile *fptr, int colnum, int naxis, long *naxes, long *blc, long *trc, long *inc, double nulval, double *array, int *anynul, int *status);
int ffgsfb(fitsfile *fptr, int colnum, int naxis, long *naxes, long *blc, long *trc, long *inc, unsigned char *array, char *flagval, int *anynul, int *status);
int ffgsfsb(fitsfile *fptr, int colnum, int naxis, long *naxes, long *blc, long *trc, long *inc, signed char *array, char *flagval, int *anynul, int *status);
int ffgsfui(fitsfile *fptr, int colnum, int naxis, long *naxes, long *blc, long *trc, long *inc, unsigned short *array, char *flagval, int *anynul, int *status);
int ffgsfi(fitsfile *fptr, int colnum, int naxis, long *naxes, long *blc, long *trc, long *inc, short *array, char *flagval, int *anynul, int *status);
int ffgsfuj(fitsfile *fptr, int colnum, int naxis, long *naxes, long *blc, long *trc, long *inc, unsigned long *array, char *flagval, int *anynul, int *status);
int ffgsfj(fitsfile *fptr, int colnum, int naxis, long *naxes, long *blc, long *trc, long *inc, long *array, char *flagval, int *anynul, int *status);
int ffgsfujj(fitsfile *fptr, int colnum, int naxis, long *naxes, long *blc, long *trc, long *inc, ULONGLONG *array, char *flagval, int *anynul, int *status);
int ffgsfjj(fitsfile *fptr, int colnum, int naxis, long *naxes, long *blc, long *trc, long *inc, LONGLONG *array, char *flagval, int *anynul, int *status);
int ffgsfuk(fitsfile *fptr, int colnum, int naxis, long *naxes, long *blc, long *trc, long *inc, unsigned int *array, char *flagval, int *anynul, int *status);
int ffgsfk(fitsfile *fptr, int colnum, int naxis, long *naxes, long *blc, long *trc, long *inc, int *array, char *flagval, int *anynul, int *status);
int ffgsfe(fitsfile *fptr, int colnum, int naxis, long *naxes, long *blc, long *trc, long *inc, float *array, char *flagval, int *anynul, int *status);
int ffgsfd(fitsfile *fptr, int colnum, int naxis, long *naxes, long *blc, long *trc, long *inc, double *array, char *flagval, int *anynul, int *status);
int ffggpb(fitsfile *fptr, long group, long firstelem, long nelem, unsigned char *array, int *status);
int ffggpsb(fitsfile *fptr, long group, long firstelem, long nelem, signed char *array, int *status);
int ffggpui(fitsfile *fptr, long group, long firstelem, long nelem, unsigned short *array, int *status);
int ffggpi(fitsfile *fptr, long group, long firstelem, long nelem, short *array, int *status);
int ffggpuj(fitsfile *fptr, long group, long firstelem, long nelem, unsigned long *array, int *status);
int ffggpj(fitsfile *fptr, long group, long firstelem, long nelem, long *array, int *status);
int ffggpujj(fitsfile *fptr, long group, long firstelem, long nelem, ULONGLONG *array, int *status);
int ffggpjj(fitsfile *fptr, long group, long firstelem, long nelem, LONGLONG *array, int *status);
int ffggpuk(fitsfile *fptr, long group, long firstelem, long nelem, unsigned int *array, int *status);
int ffggpk(fitsfile *fptr, long group, long firstelem, long nelem, int *array, int *status);
int ffggpe(fitsfile *fptr, long group, long firstelem, long nelem, float *array, int *status);
int ffggpd(fitsfile *fptr, long group, long firstelem, long nelem, double *array, int *status);
int ffgcv( fitsfile *fptr, int datatype, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, void *nulval, void *array, int *anynul, int *status);
int ffgcf( fitsfile *fptr, int datatype, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, void *array, char *nullarray, int *anynul, int *status);
int ffgcvs(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, char *nulval, char **array, int *anynul, int *status);
int ffgcl (fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, char *array, int *status);
int ffgcvl (fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, char nulval, char *array, int *anynul, int *status);
int ffgcvb(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, unsigned char nulval, unsigned char *array, int *anynul, int *status);
int ffgcvsb(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, signed char nulval, signed char *array, int *anynul, int *status);
int ffgcvui(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, unsigned short nulval, unsigned short *array, int *anynul, int *status);
int ffgcvi(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, short nulval, short *array, int *anynul, int *status);
int ffgcvuj(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, unsigned long nulval, unsigned long *array, int *anynul, int *status);
int ffgcvj(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, long nulval, long *array, int *anynul, int *status);
int ffgcvujj(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, ULONGLONG nulval, ULONGLONG *array, int *anynul, int *status);
int ffgcvjj(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, LONGLONG nulval, LONGLONG *array, int *anynul, int *status);
int ffgcvuk(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, unsigned int nulval, unsigned int *array, int *anynul, int *status);
int ffgcvk(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, int nulval, int *array, int *anynul, int *status);
int ffgcve(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, float nulval, float *array, int *anynul, int *status);
int ffgcvd(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, double nulval, double *array, int *anynul, int *status);
int ffgcvc(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, float nulval, float *array, int *anynul, int *status);
int ffgcvm(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, double nulval, double *array, int *anynul, int *status);
int ffgcx(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstbit, LONGLONG nbits, char *larray, int *status);
int ffgcxui(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG nrows, long firstbit, int nbits, unsigned short *array, int *status);
int ffgcxuk(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG nrows, long firstbit, int nbits, unsigned int *array, int *status);
int ffgcfs(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, char **array, char *nularray, int *anynul, int *status);
int ffgcfl(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, char *array, char *nularray, int *anynul, int *status);
int ffgcfb(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, unsigned char *array, char *nularray, int *anynul, int *status);
int ffgcfsb(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, signed char *array, char *nularray, int *anynul, int *status);
int ffgcfui(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, unsigned short *array, char *nularray, int *anynul, int *status);
int ffgcfi(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, short *array, char *nularray, int *anynul, int *status);
int ffgcfuj(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, unsigned long *array, char *nularray, int *anynul, int *status);
int ffgcfj(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, long *array, char *nularray, int *anynul, int *status);
int ffgcfujj(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, ULONGLONG *array, char *nularray, int *anynul, int *status);
int ffgcfjj(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, LONGLONG *array, char *nularray, int *anynul, int *status);
int ffgcfuk(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, unsigned int *array, char *nularray, int *anynul, int *status);
int ffgcfk(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, int *array, char *nularray, int *anynul, int *status);
int ffgcfe(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, float *array, char *nularray, int *anynul, int *status);
int ffgcfd(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, double *array, char *nularray, int *anynul, int *status);
int ffgcfc(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, float *array, char *nularray, int *anynul, int *status);
int ffgcfm(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, double *array, char *nularray, int *anynul, int *status);
int ffgdes(fitsfile *fptr, int colnum, LONGLONG rownum, long *length, long *heapaddr, int *status);
int ffgdesll(fitsfile *fptr, int colnum, LONGLONG rownum, LONGLONG *length, LONGLONG *heapaddr, int *status);
int ffgdess(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG nrows, long *length, long *heapaddr, int *status);
int ffgdessll(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG nrows, LONGLONG *length, LONGLONG *heapaddr, int *status);
int ffpdes(fitsfile *fptr, int colnum, LONGLONG rownum, LONGLONG length, LONGLONG heapaddr, int *status);
int fftheap(fitsfile *fptr, LONGLONG *heapsize, LONGLONG *unused, LONGLONG *overlap, int *valid, int *status);
int ffcmph(fitsfile *fptr, int *status);
int ffgtbb(fitsfile *fptr, LONGLONG firstrow, LONGLONG firstchar, LONGLONG nchars, unsigned char *values, int *status);
int ffgextn(fitsfile *fptr, LONGLONG offset, LONGLONG nelem, void *array, int *status);
int ffpextn(fitsfile *fptr, LONGLONG offset, LONGLONG nelem, void *array, int *status);
int ffppx(fitsfile *fptr, int datatype, long *firstpix, LONGLONG nelem, void *array, int *status);
int ffppxll(fitsfile *fptr, int datatype, LONGLONG *firstpix, LONGLONG nelem, void *array, int *status);
int ffppxn(fitsfile *fptr, int datatype, long *firstpix, LONGLONG nelem, void *array, void *nulval, int *status);
int ffppxnll(fitsfile *fptr, int datatype, LONGLONG *firstpix, LONGLONG nelem, void *array, void *nulval, int *status);
int ffppr(fitsfile *fptr, int datatype, LONGLONG firstelem, LONGLONG nelem, void *array, int *status);
int ffpprb(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, unsigned char *array, int *status);
int ffpprsb(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, signed char *array, int *status);
int ffpprui(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, unsigned short *array, int *status);
int ffppri(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, short *array, int *status);
int ffppruj(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, unsigned long *array, int *status);
int ffpprj(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, long *array, int *status);
int ffppruk(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, unsigned int *array, int *status);
int ffpprk(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, int *array, int *status);
int ffppre(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, float *array, int *status);
int ffpprd(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, double *array, int *status);
int ffpprjj(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, LONGLONG *array, int *status);
int ffpprujj(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, ULONGLONG *array, int *status);
int ffppru(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, int *status);
int ffpprn(fitsfile *fptr, LONGLONG firstelem, LONGLONG nelem, int *status);
int ffppn(fitsfile *fptr, int datatype, LONGLONG firstelem, LONGLONG nelem, void *array, void *nulval, int *status);
int ffppnb(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, unsigned char *array, unsigned char nulval, int *status);
int ffppnsb(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, signed char *array, signed char nulval, int *status);
int ffppnui(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, unsigned short *array, unsigned short nulval, int *status);
int ffppni(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, short *array, short nulval, int *status);
int ffppnj(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, long *array, long nulval, int *status);
int ffppnuj(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, unsigned long *array, unsigned long nulval, int *status);
int ffppnuk(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, unsigned int *array, unsigned int nulval, int *status);
int ffppnk(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, int *array, int nulval, int *status);
int ffppne(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, float *array, float nulval, int *status);
int ffppnd(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, double *array, double nulval, int *status);
int ffppnjj(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, LONGLONG *array, LONGLONG nulval, int *status);
int ffppnujj(fitsfile *fptr, long group, LONGLONG firstelem, LONGLONG nelem, ULONGLONG *array, ULONGLONG nulval, int *status);
int ffp2db(fitsfile *fptr, long group, LONGLONG ncols, LONGLONG naxis1, LONGLONG naxis2, unsigned char *array, int *status);
int ffp2dsb(fitsfile *fptr, long group, LONGLONG ncols, LONGLONG naxis1, LONGLONG naxis2, signed char *array, int *status);
int ffp2dui(fitsfile *fptr, long group, LONGLONG ncols, LONGLONG naxis1, LONGLONG naxis2, unsigned short *array, int *status);
int ffp2di(fitsfile *fptr, long group, LONGLONG ncols, LONGLONG naxis1, LONGLONG naxis2, short *array, int *status);
int ffp2duj(fitsfile *fptr, long group, LONGLONG ncols, LONGLONG naxis1, LONGLONG naxis2, unsigned long *array, int *status);
int ffp2dj(fitsfile *fptr, long group, LONGLONG ncols, LONGLONG naxis1, LONGLONG naxis2, long *array, int *status);
int ffp2duk(fitsfile *fptr, long group, LONGLONG ncols, LONGLONG naxis1, LONGLONG naxis2, unsigned int *array, int *status);
int ffp2dk(fitsfile *fptr, long group, LONGLONG ncols, LONGLONG naxis1, LONGLONG naxis2, int *array, int *status);
int ffp2de(fitsfile *fptr, long group, LONGLONG ncols, LONGLONG naxis1, LONGLONG naxis2, float *array, int *status);
int ffp2dd(fitsfile *fptr, long group, LONGLONG ncols, LONGLONG naxis1, LONGLONG naxis2, double *array, int *status);
int ffp2djj(fitsfile *fptr, long group, LONGLONG ncols, LONGLONG naxis1, LONGLONG naxis2, LONGLONG *array, int *status);
int ffp2dujj(fitsfile *fptr, long group, LONGLONG ncols, LONGLONG naxis1, LONGLONG naxis2, ULONGLONG *array, int *status);
int ffp3db(fitsfile *fptr, long group, LONGLONG ncols, LONGLONG nrows, LONGLONG naxis1, LONGLONG naxis2, LONGLONG naxis3, unsigned char *array, int *status);
int ffp3dsb(fitsfile *fptr, long group, LONGLONG ncols, LONGLONG nrows, LONGLONG naxis1, LONGLONG naxis2, LONGLONG naxis3, signed char *array, int *status);
int ffp3dui(fitsfile *fptr, long group, LONGLONG ncols, LONGLONG nrows, LONGLONG naxis1, LONGLONG naxis2, LONGLONG naxis3, unsigned short *array, int *status);
int ffp3di(fitsfile *fptr, long group, LONGLONG ncols, LONGLONG nrows, LONGLONG naxis1, LONGLONG naxis2, LONGLONG naxis3, short *array, int *status);
int ffp3duj(fitsfile *fptr, long group, LONGLONG ncols, LONGLONG nrows, LONGLONG naxis1, LONGLONG naxis2, LONGLONG naxis3, unsigned long *array, int *status);
int ffp3dj(fitsfile *fptr, long group, LONGLONG ncols, LONGLONG nrows, LONGLONG naxis1, LONGLONG naxis2, LONGLONG naxis3, long *array, int *status);
int ffp3duk(fitsfile *fptr, long group, LONGLONG ncols, LONGLONG nrows, LONGLONG naxis1, LONGLONG naxis2, LONGLONG naxis3, unsigned int *array, int *status);
int ffp3dk(fitsfile *fptr, long group, LONGLONG ncols, LONGLONG nrows, LONGLONG naxis1, LONGLONG naxis2, LONGLONG naxis3, int *array, int *status);
int ffp3de(fitsfile *fptr, long group, LONGLONG ncols, LONGLONG nrows, LONGLONG naxis1, LONGLONG naxis2, LONGLONG naxis3, float *array, int *status);
int ffp3dd(fitsfile *fptr, long group, LONGLONG ncols, LONGLONG nrows, LONGLONG naxis1, LONGLONG naxis2, LONGLONG naxis3, double *array, int *status);
int ffp3djj(fitsfile *fptr, long group, LONGLONG ncols, LONGLONG nrows, LONGLONG naxis1, LONGLONG naxis2, LONGLONG naxis3, LONGLONG *array, int *status);
int ffp3dujj(fitsfile *fptr, long group, LONGLONG ncols, LONGLONG nrows, LONGLONG naxis1, LONGLONG naxis2, LONGLONG naxis3, ULONGLONG *array, int *status);
int ffpss(fitsfile *fptr, int datatype, long *fpixel, long *lpixel, void *array, int *status);
int ffpssb(fitsfile *fptr, long group, long naxis, long *naxes, long *fpixel, long *lpixel, unsigned char *array, int *status);
int ffpsssb(fitsfile *fptr, long group, long naxis, long *naxes, long *fpixel, long *lpixel, signed char *array, int *status);
int ffpssui(fitsfile *fptr, long group, long naxis, long *naxes, long *fpixel, long *lpixel, unsigned short *array, int *status);
int ffpssi(fitsfile *fptr, long group, long naxis, long *naxes, long *fpixel, long *lpixel, short *array, int *status);
int ffpssuj(fitsfile *fptr, long group, long naxis, long *naxes, long *fpixel, long *lpixel, unsigned long *array, int *status);
int ffpssj(fitsfile *fptr, long group, long naxis, long *naxes, long *fpixel, long *lpixel, long *array, int *status);
int ffpssuk(fitsfile *fptr, long group, long naxis, long *naxes, long *fpixel, long *lpixel, unsigned int *array, int *status);
int ffpssk(fitsfile *fptr, long group, long naxis, long *naxes, long *fpixel, long *lpixel, int *array, int *status);
int ffpsse(fitsfile *fptr, long group, long naxis, long *naxes, long *fpixel, long *lpixel, float *array, int *status);
int ffpssd(fitsfile *fptr, long group, long naxis, long *naxes, long *fpixel, long *lpixel, double *array, int *status);
int ffpssjj(fitsfile *fptr, long group, long naxis, long *naxes, long *fpixel, long *lpixel, LONGLONG *array, int *status);
int ffpssujj(fitsfile *fptr, long group, long naxis, long *naxes, long *fpixel, long *lpixel, ULONGLONG *array, int *status);
int ffpgpb(fitsfile *fptr, long group, long firstelem, long nelem, unsigned char *array, int *status);
int ffpgpsb(fitsfile *fptr, long group, long firstelem, long nelem, signed char *array, int *status);
int ffpgpui(fitsfile *fptr, long group, long firstelem, long nelem, unsigned short *array, int *status);
int ffpgpi(fitsfile *fptr, long group, long firstelem, long nelem, short *array, int *status);
int ffpgpuj(fitsfile *fptr, long group, long firstelem, long nelem, unsigned long *array, int *status);
int ffpgpj(fitsfile *fptr, long group, long firstelem, long nelem, long *array, int *status);
int ffpgpuk(fitsfile *fptr, long group, long firstelem, long nelem, unsigned int *array, int *status);
int ffpgpk(fitsfile *fptr, long group, long firstelem, long nelem, int *array, int *status);
int ffpgpe(fitsfile *fptr, long group, long firstelem, long nelem, float *array, int *status);
int ffpgpd(fitsfile *fptr, long group, long firstelem, long nelem, double *array, int *status);
int ffpgpjj(fitsfile *fptr, long group, long firstelem, long nelem, LONGLONG *array, int *status);
int ffpgpujj(fitsfile *fptr, long group, long firstelem, long nelem, ULONGLONG *array, int *status);
int fits_iter_set_by_name(iteratorCol *col, fitsfile *fptr, char *colname, int datatype, int iotype);
int fits_iter_set_by_num(iteratorCol *col, fitsfile *fptr, int colnum, int datatype, int iotype);
int fits_iter_set_file(iteratorCol *col, fitsfile *fptr);
int fits_iter_set_colname(iteratorCol *col, char *colname);
int fits_iter_set_colnum(iteratorCol *col, int colnum);
int fits_iter_set_datatype(iteratorCol *col, int datatype);
int fits_iter_set_iotype(iteratorCol *col, int iotype);
fitsfile * fits_iter_get_file(iteratorCol *col);
char * fits_iter_get_colname(iteratorCol *col);
int fits_iter_get_colnum(iteratorCol *col);
int fits_iter_get_datatype(iteratorCol *col);
int fits_iter_get_iotype(iteratorCol *col);
void *fits_iter_get_array(iteratorCol *col);
long fits_iter_get_tlmin(iteratorCol *col);
long fits_iter_get_tlmax(iteratorCol *col);
long fits_iter_get_repeat(iteratorCol *col);
char *fits_iter_get_tunit(iteratorCol *col);
char *fits_iter_get_tdisp(iteratorCol *col);
int ffiter(int ncols, iteratorCol *data, long offset, long nPerLoop, int (*workFn)( long totaln, long offset, long firstn, long nvalues, int narrays, iteratorCol *data, void *userPointer), void *userPointer, int *status);
int ffpcl(fitsfile *fptr, int datatype, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, void *array, int *status);
int ffpcls(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, char **array, int *status);
int ffpcll(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, char *array, int *status);
int ffpclb(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, unsigned char *array, int *status);
int ffpclsb(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, signed char *array, int *status);
int ffpclui(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, unsigned short *array, int *status);
int ffpcli(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, short *array, int *status);
int ffpcluj(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, unsigned long *array, int *status);
int ffpclj(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, long *array, int *status);
int ffpcluk(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, unsigned int *array, int *status);
int ffpclk(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, int *array, int *status);
int ffpcle(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, float *array, int *status);
int ffpcld(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, double *array, int *status);
int ffpclc(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, float *array, int *status);
int ffpclm(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, double *array, int *status);
int ffpclu(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, int *status);
int ffprwu(fitsfile *fptr, LONGLONG firstrow, LONGLONG nrows, int *status);
int ffpcljj(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, LONGLONG *array, int *status);
int ffpclujj(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, ULONGLONG *array, int *status);
int ffpclx(fitsfile *fptr, int colnum, LONGLONG frow, long fbit, long nbit, char *larray, int *status);
int ffpcn(fitsfile *fptr, int datatype, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, void *array, void *nulval, int *status);
int ffpcns( fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, char **array, char *nulvalue, int *status);
int ffpcnl( fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, char *array, char nulvalue, int *status);
int ffpcnb(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, unsigned char *array, unsigned char nulvalue, int *status);
int ffpcnsb(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, signed char *array, signed char nulvalue, int *status);
int ffpcnui(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, unsigned short *array, unsigned short nulvalue, int *status);
int ffpcni(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, short *array, short nulvalue, int *status);
int ffpcnuj(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, unsigned long *array, unsigned long nulvalue, int *status);
int ffpcnj(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, long *array, long nulvalue, int *status);
int ffpcnuk(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, unsigned int *array, unsigned int nulvalue, int *status);
int ffpcnk(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, int *array, int nulvalue, int *status);
int ffpcne(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, float *array, float nulvalue, int *status);
int ffpcnd(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, double *array, double nulvalue, int *status);
int ffpcnjj(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, LONGLONG *array, LONGLONG nulvalue, int *status);
int ffpcnujj(fitsfile *fptr, int colnum, LONGLONG firstrow, LONGLONG firstelem, LONGLONG nelem, ULONGLONG *array, ULONGLONG nulvalue, int *status);
int ffptbb(fitsfile *fptr, LONGLONG firstrow, LONGLONG firstchar, LONGLONG nchars, unsigned char *values, int *status);
int ffirow(fitsfile *fptr, LONGLONG firstrow, LONGLONG nrows, int *status);
int ffdrow(fitsfile *fptr, LONGLONG firstrow, LONGLONG nrows, int *status);
int ffdrrg(fitsfile *fptr, char *ranges, int *status);
int ffdrws(fitsfile *fptr, long *rownum, long nrows, int *status);
int ffdrwsll(fitsfile *fptr, LONGLONG *rownum, LONGLONG nrows, int *status);
int fficol(fitsfile *fptr, int numcol, char *ttype, char *tform, int *status);
int fficls(fitsfile *fptr, int firstcol, int ncols, char **ttype, char **tform, int *status);
int ffmvec(fitsfile *fptr, int colnum, LONGLONG newveclen, int *status);
int ffdcol(fitsfile *fptr, int numcol, int *status);
int ffcpcl(fitsfile *infptr, fitsfile *outfptr, int incol, int outcol, int create_col, int *status);
int ffccls(fitsfile *infptr, fitsfile *outfptr, int incol, int outcol, int ncols, int create_col, int *status);
int ffcprw(fitsfile *infptr, fitsfile *outfptr, LONGLONG firstrow, LONGLONG nrows, int *status);
int ffcpht(fitsfile *infptr, fitsfile *outfptr, LONGLONG firstrow, LONGLONG nrows, int *status);
int ffgics(fitsfile *fptr, double *xrval, double *yrval, double *xrpix, double *yrpix, double *xinc, double *yinc, double *rot, char *type, int *status);
int ffgicsa(fitsfile *fptr, char version, double *xrval, double *yrval, double *xrpix, double *yrpix, double *xinc, double *yinc, double *rot, char *type, int *status);
int ffgtcs(fitsfile *fptr, int xcol, int ycol, double *xrval, double *yrval, double *xrpix, double *yrpix, double *xinc, double *yinc, double *rot, char *type, int *status);
int ffwldp(double xpix, double ypix, double xref, double yref, double xrefpix, double yrefpix, double xinc, double yinc, double rot, char *type, double *xpos, double *ypos, int *status);
int ffxypx(double xpos, double ypos, double xref, double yref, double xrefpix, double yrefpix, double xinc, double yinc, double rot, char *type, double *xpix, double *ypix, int *status);
int ffgiwcs(fitsfile *fptr, char **header, int *status);
int ffgtwcs(fitsfile *fptr, int xcol, int ycol, char **header, int *status);
int fftexp( fitsfile *fptr, char *expr, int maxdim, int *datatype, long *nelem, int *naxis, long *naxes, int *status );
int fffrow( fitsfile *infptr, char *expr, long firstrow, long nrows, long *n_good_rows, char *row_status, int *status);
int ffffrw( fitsfile *fptr, char *expr, long *rownum, int *status);
int fffrwc( fitsfile *fptr, char *expr, char *timeCol, char *parCol, char *valCol, long ntimes, double *times, char *time_status, int *status );
int ffsrow( fitsfile *infptr, fitsfile *outfptr, char *expr, int *status);
int ffcrow( fitsfile *fptr, int datatype, char *expr, long firstrow, long nelements, void *nulval, void *array, int *anynul, int *status );
int ffcalc_rng( fitsfile *infptr, char *expr, fitsfile *outfptr, char *parName, char *parInfo, int nRngs, long *start, long *end, int *status );
int ffcalc( fitsfile *infptr, char *expr, fitsfile *outfptr, char *parName, char *parInfo, int *status );
int ffhist(fitsfile **fptr, char *outfile, int imagetype, int naxis, char colname[4][71], double *minin, double *maxin, double *binsizein, char minname[4][71], char maxname[4][71], char binname[4][71], double weightin, char wtcol[71], int recip, char *rowselect, int *status);
int ffhist2(fitsfile **fptr, char *outfile, int imagetype, int naxis, char colname[4][71], double *minin, double *maxin, double *binsizein, char minname[4][71], char maxname[4][71], char binname[4][71], double weightin, char wtcol[71], int recip, char *rowselect, int *status);
fitsfile *ffhist3(fitsfile *fptr, char *outfile, int imagetype, int naxis, char colname[4][71], double *minin, double *maxin, double *binsizein, char minname[4][71], char maxname[4][71], char binname[4][71], double weightin, char wtcol[71], int recip, char *selectrow, int *status);
int fits_select_image_section(fitsfile **fptr, char *outfile, char *imagesection, int *status);
int fits_copy_image_section(fitsfile *infptr, fitsfile *outfile, char *imagesection, int *status);
int fits_calc_binning(fitsfile *fptr, int naxis, char colname[4][71], double *minin, double *maxin, double *binsizein, char minname[4][71], char maxname[4][71], char binname[4][71], int *colnum, long *haxes, float *amin, float *amax, float *binsize, int *status);
int fits_calc_binningd(fitsfile *fptr, int naxis, char colname[4][71], double *minin, double *maxin, double *binsizein, char minname[4][71], char maxname[4][71], char binname[4][71], int *colnum, long *haxes, double *amin, double *amax, double *binsize, int *status);
int fits_write_keys_histo(fitsfile *fptr, fitsfile *histptr, int naxis, int *colnum, int *status);
int fits_rebin_wcs( fitsfile *fptr, int naxis, float *amin, float *binsize, int *status);
int fits_rebin_wcsd( fitsfile *fptr, int naxis, double *amin, double *binsize, int *status);
int fits_make_hist(fitsfile *fptr, fitsfile *histptr, int bitpix,int naxis, long *naxes, int *colnum, float *amin, float *amax, float *binsize, float weight, int wtcolnum, int recip, char *selectrow, int *status);
int fits_make_histd(fitsfile *fptr, fitsfile *histptr, int bitpix,int naxis, long *naxes, int *colnum, double *amin, double *amax, double *binsize, double weight, int wtcolnum, int recip, char *selectrow, int *status);
typedef struct { int count;
char ** path;
char ** tag;
fitsfile ** ifptr;
char * expression;
int bitpix;
long blank;
fitsfile * ofptr;
char keyword[75];
char comment[73];
} PixelFilter;
int fits_pixel_filter (PixelFilter * filter, int * status);
int ffgtcr(fitsfile *fptr, char *grpname, int grouptype, int *status);
int ffgtis(fitsfile *fptr, char *grpname, int grouptype, int *status);
int ffgtch(fitsfile *gfptr, int grouptype, int *status);
int ffgtrm(fitsfile *gfptr, int rmopt, int *status);
int ffgtcp(fitsfile *infptr, fitsfile *outfptr, int cpopt, int *status);
int ffgtmg(fitsfile *infptr, fitsfile *outfptr, int mgopt, int *status);
int ffgtcm(fitsfile *gfptr, int cmopt, int *status);
int ffgtvf(fitsfile *gfptr, long *firstfailed, int *status);
int ffgtop(fitsfile *mfptr,int group,fitsfile **gfptr,int *status);
int ffgtam(fitsfile *gfptr, fitsfile *mfptr, int hdupos, int *status);
int ffgtnm(fitsfile *gfptr, long *nmembers, int *status);
int ffgmng(fitsfile *mfptr, long *nmembers, int *status);
int ffgmop(fitsfile *gfptr, long member, fitsfile **mfptr, int *status);
int ffgmcp(fitsfile *gfptr, fitsfile *mfptr, long member, int cpopt, int *status);
int ffgmtf(fitsfile *infptr, fitsfile *outfptr, long member, int tfopt, int *status);
int ffgmrm(fitsfile *fptr, long member, int rmopt, int *status);
int fits_execute_template(fitsfile *ff, char *ngp_template, int *status);
int fits_img_stats_short(short *array,long nx, long ny, int nullcheck, short nullvalue,long *ngoodpix, short *minvalue, short *maxvalue, double *mean, double *sigma, double *noise1, double *noise2, double *noise3, double *noise5, int *status);
int fits_img_stats_int(int *array,long nx, long ny, int nullcheck, int nullvalue,long *ngoodpix, int *minvalue, int *maxvalue, double *mean, double *sigma, double *noise1, double *noise2, double *noise3, double *noise5, int *status);
int fits_img_stats_float(float *array, long nx, long ny, int nullcheck, float nullvalue,long *ngoodpix, float *minvalue, float *maxvalue, double *mean, double *sigma, double *noise1, double *noise2, double *noise3, double *noise5, int *status);
int fits_set_compression_type(fitsfile *fptr, int ctype, int *status);
int fits_set_tile_dim(fitsfile *fptr, int ndim, long *dims, int *status);
int fits_set_noise_bits(fitsfile *fptr, int noisebits, int *status);
int fits_set_quantize_level(fitsfile *fptr, float qlevel, int *status);
int fits_set_hcomp_scale(fitsfile *fptr, float scale, int *status);
int fits_set_hcomp_smooth(fitsfile *fptr, int smooth, int *status);
int fits_set_quantize_method(fitsfile *fptr, int method, int *status);
int fits_set_quantize_dither(fitsfile *fptr, int dither, int *status);
int fits_set_dither_seed(fitsfile *fptr, int seed, int *status);
int fits_set_dither_offset(fitsfile *fptr, int offset, int *status);
int fits_set_lossy_int(fitsfile *fptr, int lossy_int, int *status);
int fits_set_huge_hdu(fitsfile *fptr, int huge, int *status);
int fits_set_compression_pref(fitsfile *infptr, fitsfile *outfptr, int *status);
int fits_get_compression_type(fitsfile *fptr, int *ctype, int *status);
int fits_get_tile_dim(fitsfile *fptr, int ndim, long *dims, int *status);
int fits_get_quantize_level(fitsfile *fptr, float *qlevel, int *status);
int fits_get_noise_bits(fitsfile *fptr, int *noisebits, int *status);
int fits_get_hcomp_scale(fitsfile *fptr, float *scale, int *status);
int fits_get_hcomp_smooth(fitsfile *fptr, int *smooth, int *status);
int fits_get_dither_seed(fitsfile *fptr, int *seed, int *status);
int fits_img_compress(fitsfile *infptr, fitsfile *outfptr, int *status);
int fits_comp_img(fitsfile *infptr, fitsfile *outfptr, int compress_type, long *tilesize, int parm1, int parm2, int *status);
int fits_is_compressed_image(fitsfile *fptr, int *status);
int fits_is_reentrant(void);
int fits_decomp_img (fitsfile *infptr, fitsfile *outfptr, int *status);
int fits_img_decompress_header(fitsfile *infptr, fitsfile *outfptr, int *status);
int fits_img_decompress (fitsfile *infptr, fitsfile *outfptr, int *status);
int fits_hcompress(int *a, int nx, int ny, int scale, char *output, long *nbytes, int *status);
int fits_hcompress64(LONGLONG *a, int nx, int ny, int scale, char *output, long *nbytes, int *status);
int fits_hdecompress(unsigned char *input, int smooth, int *a, int *nx, int *ny, int *scale, int *status);
int fits_hdecompress64(unsigned char *input, int smooth, LONGLONG *a, int *nx, int *ny, int *scale, int *status);
int fits_compress_table (fitsfile *infptr, fitsfile *outfptr, int *status);
int fits_uncompress_table(fitsfile *infptr, fitsfile *outfptr, int *status);
int ffihtps(void);
int ffchtps(void);
void ffvhtps(int flag);
void ffshdwn(int flag);
int ffgtmo(void);
int ffstmo(int sec, int *status);
/* END /usr/include/fitsio.h */
]]
return ffi.load 'cfitsio'
