-- GLES on OSX isn't present soo ...
-- meanwhile all this works completely fine - GLES and GL - emulated IN A BROWSER, ON OSX ... 
-- IT WORKS ON OSX IN A BROWSER BUT NOT WHEN RUN FROM THE OS ITSELF?!?!?!?!?!?!?
return require 'ffi.req' 'OpenGL'
